### ISSUE TITLE
XP 6

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#172]
# Scope of Change

The next major XP framework release will bring a magnitude of new features.
# Rationale

This RFC gives a strategic outlook to the further development.
# Functionality

The XP 6 series are not backwards compatible - code written in XP 5 will not work and will need to be converted. The XP 5 series will be continued for a while before being phased out.
## Core only.

See the separate RFCs #262, #278 and #287 
## PHP 5.4+

This XP Framework version requires a PHP version greater than or equal to 5.4.0. See RFC #281.
## Namespaces

All XP classes will be inside namespaces. This supersedes the functionality implemented in xp-framework/rfc#37 and makes all classnames always fully qualified (but allows for short notation by using "use"). See xp-framework/rfc#136, step 2: For classes imported by `uses()`, short aliases will be created. Other classes only exist via there fully qualified name.
## Unicode

Unicode (see xp-framework/rfc#146) support will be added. All strings are to be considered being `utf-8`. The HTTP, command line, rdbms, LDAP, FTP, web services, files and other APIs will be changed to handle Unicode. The user should not need to encode or decode manually.
## Using

The `with()` "statement" will be extended to support the `lang.Closeable` interface. It closes all parameters after running the block - even when that yields an exception.

``` php
with (new FileReader(__FILE__), new FileWriter('php://stdout'), function($in, $out) {
  $out->write($in->read());
});
```
# Security considerations

n/a
# Speed impact

n/a
# Dependencies

There are now new dependencies, PHP 5.3 is kept as minimum version.
## Deprecations

The following are no longer needed or required:
- The uses() statement (replaced by "use" and __autoload)
- xp-framework/rfc#37 (superseded by namespaces)
- Enum::values() in declaration (made unnecessary by late static binding)
- SAPI feature removal: See xp-framework/rfc#186
- The ref() and deref() functions
- The `$__generic`-style generics (BC with < 5.8)
## BC problems

These issues are to be considered problematic:
- Serialization format has changed in PHP 5.3
- All classes are now namespaced, cases where the unqualified class names are used need to be changed
# Related documents
- Namespaces: See xp-framework/rfc#136
- PHP 5.3 experiments: http://experiments.xp-forge.net/xml/browse?arena,five3
- Namespaces - [For Step 2 (XP 6.0.0)](https://github.com/xp-framework/rfc/issues/136#issuecomment-4092352)

**Comment by thekid** [comment]
Announcement @ http://news.planet-xp.net/article/559/2013/11/09/XP_6_plans

**Comment by thekid** [comment]
First alpha release available at https://github.com/xp-framework/core/releases/tag/v6.0.0alpha1. To use it, download the _xp-6.0.0alpha1.zip_ file and unzip.

``` sh
$ wget https://github.com/xp-framework/core/releases/download/v6.0.0alpha1/xp-6.0.0alpha1.zip
$ unzip xp-6.0.0alpha1.zip && rm xp-6.0.0alpha1.zip
# ...

$ USE_XP=6.0.0alpha1 xp -v
XP 6.0.0-dev { PHP 5.5.9 & ZE 2.5.0 } @ Windows NT SLATE 6.2 build 9200...
Copyright (c) 2001-2013 the XP group
ArchiveCL<...\xp\6.0.0alpha1\lib\xp-rt-6.0.0alpha1.xar>
FileSystemCL<...\xp\>
```

Known issues (_visible above :smile:_)
- Version number incorrect
- Copyright outdated

**Comment by thekid** [comment]
Second alpha release available at https://github.com/xp-framework/core/releases/tag/v6.0.0alpha2. Installation goes as above, the known issues mentioned above have been fixed.

**Comment by thekid** [comment]
After 7 alphas and 3 betas we are finally live!

**Comment by kiesel** [comment]
Yay! :+1:
