### ISSUE TITLE
Support different kinds of class archive file formats

### ISSUE THREAD

**Issue by kiesel** [xp-framework/rfc#206]
# Scope of Change

Provide means to register class loaders for different kinds of file formats,
and - thus - extensions.
# Rationale

For interoperability w/ different languages and toolchains, different kinds
of file format should be supported.
# Functionality

To be elaborated. 
# Security considerations

There should be no network file class loader support.
# Speed impact

To be elaborated.
# Dependencies
# Related documents

**Comment by thekid** [comment]
You can do this by adding arbitrary class loaders inside module.xp. This is what [the XP compiler](https://github.com/xp-lang/compiler) does:

``` php
<?php namespace xp\compiler;

use lang\ClassLoader;

define('MODIFIER_PACKAGE',  2048);
define('MODIFIER_INLINE',   4096);
define('MODIFIER_NATIVE',   8192);
define('DETAIL_PROPERTY',      0);

/**
 * XP Compiler
 */
module xp-lang/compiler {

  /** @return void */
  public function initialize() {
    ClassLoader::registerLoader(JitClassLoader::instanceFor(realpath('.')), true);
  }
}
```
