### ISSUE TITLE
Coding standards update: PHP 5.3 namespaces

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#208]
# Scope of change

The official XP Framework coding standards will be adjusted for new sourcecode using PHP 5.3 namespaces, and will include breaking changes. The old coding standards will be left untouched as to not suddenly un-comply all existing files. Affected are indentation, file header, namespace and use statements, as well as class names.
# Rationale

Adjust to modern-day sourcecode and infrastructure.
# Functionality

In alignment with the motto **"alright then, show me the code"** - here's an overview of a PHP class file adhering to the new standards:

``` php
<?php namespace com\example\module\tests;

use com\example\module\api\Fixture;

/**
 * Tests the Fixture class
 */
class FixtureTest extends \unittest\TestCase {

  /**
   * Helper method to create a new fixture
   *
   * @param  bool $connect
   * @return   com.example.module.api.Fixture
   */
  protected function newFixture($connect= false) {
    return new Fixture($connect);
  }

  /**
   * Tests constructor
   */
  #[@test]
  public function can_create() {
    $this->newFixture();
  }
}
```
## The differences
- The file header including the `$Id$` tag (or actually, its expanded form) is gone. See http://stackoverflow.com/questions/384108/moving-from-cvs-to-git-id-equivalent for reasoning
- The `namespace` statement comes right after the opening PHP tag.
- No more `uses()` - namespaces and autoloading have replaced this
- Top-level statements such as `use` and `class` or `interface` starts at beginning of line instead of being indented 2 characters
- Parameters have `$` signs inside apidoc
- The literals `null`, `false` and `true` are regarded like keywords and no longer like constants and thus in lowercase
- No _required_ newline between method apidoc and first `@...` tag - our recommendation is to use one, though
- Unittest methods may use underscore notation (and may omit api documentation)
- No closing PHP tag - our strong recommendation is to omit it, though it is allowed.
### Unicode

All files adhering to the new coding standard are to be stored in UTF-8 without BOM.
### APIDoc markup

Inside api documentation, use GitHub-flavored markdown for markup instead of HTML.

Example:

`````` php
/**
 * Fixture
 *
 * ## Example
 * ```php
 * $fixture= new Fixture();
 * ```
 */
``````
### No more `@purpose`

The purpose of a class should already have been described inside the free text comment. The original idea, to see which classes serve as internal and where the entry point to an API is, can be controlled via `package-info.xp`.
### Namespace names

Namespaces are in all-lowercase, as package names have always been, and use the reverse-domain principile for anything but the core classes.
### Class names

We want to keep the ways to determine a fully qualified class name while reading code to a minimum. We therefore define:
- No `use ... *as* ...`.
- No relative class names, e.g. inside `namespace com\example\module`, a use statement reading `use api\Fixture` or the use of `api\Fixture` as a class name is prohibited. 

You must always use either an unqualified name (and a use statement, if the class is inside another namespace) or the fully qualified name (beginning with a leading backslash `\`).
# Security considerations

n/a
# Speed impact

None.
# Dependencies
- Update to coding standards https://github.com/xp-framework/xp-framework/wiki/codingstandards
# Related documents
- http://www.php.net/manual/en/language.namespaces.importing.php
- https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md
- http://www.dartlang.org/articles/style-guide/
- https://help.github.com/articles/github-flavored-markdown

**Comment by thekid** [comment]
Open questions:
- [x] Should we define these new files always use UTF-8 encoding (without BOM)?
- [x] Should we follow various other existing coding guidelines and define `true`, `false` and `null` to be lowercase (aligned with keywords, instead of constants)?
- [x] We should most probably note the deprecation of the `@purpose` tag.
- [x] Should we define the apidocs to use (GH-) markdown?

**Comment by mrosoiu** [comment]
+1 Looks good. Also 'yes' on all 4 questions.

**Comment by thekid** [comment]
@mrosoiu - thanks!

Added answers to all four questions to the RFC text.

**Comment by thekid** [comment]
By the way:

> Unittest methods may use underscore notation

This has been common practice for a while - IIRC it was suggested by @iigorr. Simply being explicit about it here now.

See also http://stackoverflow.com/questions/155436/unit-test-naming-best-practices

**Comment by thekid** [comment]
Announcement @ http://news.planet-xp.net/article/517/2013/04/27/ + Twitter + FB + ONE

**Comment by kiesel** [comment]
Having used it in a library now, I must say I like relative namespaces when writing code. It makes code simpler to write - but you're probably right in the long term about readability.
- +1 for UTF-8
- +1 for lowercased true, false, null
- +1 for GH-markdown support for apidocs
- +1 for deprecation of `@purpose`

**Comment by kiesel** [comment]
One thing: while inside a namespace, eg. `\com\example\api`, a reference to a class `Client` in the same namespace is actually also a relative namespace lookup - resulting in class `\com\example\api\Client`. Should that be forbidden? I think not.

**Comment by thekid** [comment]
> Should that be forbidden? I think not.

No. I've tried clarifying this in the text above.

There are three allowed usecases:
1. We have the fully qualified version, e.g. `\com\example\api\Client`, in the code -> the `Client` class comes from the `com\example\api` namespace.
2. We have an unqualified version, e.g. `Client` in the code **and** a use statement at the top, e.g. `use  com\example\api\Client` -> the `Client` class comes from the `com\example\api` namespace.
3. We have an unqualified version, e.g. `Client` in the code and **no use statement** -> the `Client` class is inside the same namespace as the class it's used in.

What we don't want is more possibilities than these.

**Comment by thekid** [comment]
Changes incorporated into the Wiki.
- https://github.com/xp-framework/xp-framework/wiki/codingstandards now contains the new coding standards
- https://github.com/xp-framework/xp-framework/wiki/codingstandardsold contains the old ones for un-namespaced code.
