### ISSUE TITLE
parent()

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#213]
Instead of `parent::method($arg1, $arg2)` the syntax could be shortened to `parent($arg1, $arg2)`.

**Comment by ppetermann** [comment]
how do you identify what method of the parent would be called by that?

**Comment by thekid** [comment]
This is done inside the XP Compiler. Take for example:

``` xp
  public void setId(int $id) {
    if ($id < 0 || $id > $this.max) {
      throw new IllegalArgumentException('Given ID outside range 0..' ~ $this.max);
    }
    parent($id);
  }
```

Looking at the `parent` statement, we know which method it exists in and then rewrite this to `parent::setId($id);` inside the compilation phase.

At runtime, we could do the same using `debug_backtrace()` if we wanted to, but that's quite slow:)

**Comment by ppetermann** [comment]
ah, so its just calling parents method of the same name as the current method.

personally i find this is rather obfuscating the code than helping,
also you might want to consider that in php while there would be no real conflict, 
it might confuse people that

```
parent($arg1);
```

would be calling the parents setId,
while  

```
new parent($arg1) 
```

would create a new object of the parents type calling the constructor.
again, its not a real issue, but it might confuse people.

**Comment by thekid** [comment]
Today, `parent($arg1)` calls a global function, while `new parent($arg1);` create a new object of the parent's type:-)

**Comment by ppetermann** [comment]
thats correct, but has the same issue of creating confusing code when used ;)
