### ISSUE TITLE
Add accessor for XP Framework version

### ISSUE THREAD

**Issue by kiesel** [xp-framework/rfc#215]
# Scope of change

A new method `xp::version()` will be added, returning the trimmed contents of the VERSION file provided by the `lang.Object` classloader.

---
# Rationale

This information can be used for debugging, or logging output - or eg. client information.

---
# Functionality

The `VERSION` file provided by the classloader that `lang.Object` provided will be read to provide the version. It is supposed to be shipped in the final XAR, as well as it is available on all development checkouts.

The standalone implementation of `xp.runtime.Version` will be removed, the method there will just use the new implementation.

---
# Security considerations

n/a

---
# Speed impact

None.

---
# Dependencies

None.

---
# Related documents
- Original pull requests at xp-framework/xp-framework#57

**Comment by thekid** [comment]
+1 for xp5_9
