### ISSUE TITLE
REST server API implementation

### ISSUE THREAD

**Issue by kiesel** [xp-framework/rfc#216]
# Scope of Change

Beside of other types of webserives (e.g. SOAP, JSON) support for REST, which is a resource based type of webservice, will be added to the framework.
# Rationale

Currently few types of webservices are supported but the standard for webservices is now REST: it's flexible, it's simple and easy to use.
# Functionality

Since all webservice implementation are in the <code>webservice</code> package, the REST implmenetation will also be there.
## Packages

The following packages currently exists:
- <tt>webservices.json</tt>
- <tt>webservices.soap</tt>
- <tt>webservices.uddi</tt>
- <tt>webservices.wddx</tt>
- <tt>webservices.xmlrpc</tt>

A new package will be created there containing the REST implementation:
- <tt>webservices.rest</tt>
## Architecture

The entry point for a webservice is a scriptlet since it is accessible via HTTP. The basic implementation <code>scriptlet.http.HttpScriptlet</code> will be extended to new scriptlet providing functions for handling the
requests.

The request is received by the scriptlet which will then ask a router to return a valid route for the request. When a route can not be found an exception will be thrown. In case a route can be found the route will be processed.

The router itself contains a routing table and a routing processor. The routing table contains configured routing items which each of them has a verb, a path and a target configured. The routing processor is responsible to process a route, e.g. by invoking them and passing the required arguments to it.

To have support for multiple content types, e.g. JSON or XML, the scriptlets request and response will not be passed directly to the handler functions. Instead adapter instances will be used and passed to the handler which provide common functionality for accessing request and response properties.
## Entry point

As mentioned above, the entry point will be a scriptlet which extends the <code>HttpScriptlet</code>. The <code>webservices.rest.server.RestHttpScriptlet</code> contains the main functionality for receiving a request and providing a response.

Additonally to this is also does the routing processing by using a router. The router is asked for a matching route for the current request and response. After this the route is processed by a routing processor.
## Routing

The routing is managed by a <code>webservices.rest.server.routing.RestRouter</code>, which is only an interface for the routing logic, which stores a routing table containing all valid routes, named <code>webservices.rest.server.routing.RestRouting</code>.

A router implementation will be provided which routes requests based on annotation to given handler and function: <code>webservices.rest.server.routing.RestAnnotationRouter</code>. It will scan for handler classes in a given package and will build a <code>RestRouting</code> table based on the annotations in the classes.

Here are some examples how to configure this routing by annotations:

``` php
#@webservice
class TheService extends Object {

  #[@webmethod(verb= 'GET', path= '/data')]
  public function getSomething() { }

  #[@webmethod(verb= 'GET', path= '/item/{id}')]
  public function getSomething($id) { }

  #[@webmethod(verb= 'PUT', path= '/item/{id}', inject= array('id', 'payload'))]
  public function saveSomething($id, $data) { }
}
```

First of all the class needs to be declared as REST handler by using the <tt>@webmethod</tt> annotation. All functions of this class which should be accessible by the webservice needs to declare the <tt>@webmethod</tt> annotation.

There are the following settings which can be used in the <tt>@webmethod</tt> annotation to configure the routing:
- <tt>verb</tt> - only route request with given HTTP method (GET, POST, PUT, ...)
- <tt>path</tt> - only route request matching this path (you can use placeholders if you need some values from the path by using "{var}")
- <tt>inject</tt> - declare which values should be injected to the function when invoking it (if omitted parameters will be matched against the function argument names, otherwise only the named parameters will be passed - exception: use "payload" to get the body's data)

This is the only implementation which will be available, but can be extended by implementing the <code>RestRouter</code> interface in a different way.
## Routing items

All router implementations will build a routing table as mentioned already above. The resulting <code>RestRouting</code> table contains for each route a <code>webservice.rest.server.routing.RestRoutingItem</code> which represents
a route. A route itself have the following properties:
- <tt>verb</tt> - a simple string containing the verb (e.g. <tt>GET</tt>, <tt>POST</tt>, ...)
- <tt>path</tt> - a <code>webservices.rest.server.routing.RestPath</code> representing the matching path pattern for the route
- <tt>target</tt> - a <code>webservices.rest.server.routing.RestRoute</code> representing the target to process (e.g. invoke a method)
- <tt>args</tt> - a <code>webservices.rest.server.routing.RestRoutingArgs</code> which contains the argument for route processing
## Routing targets

The routing target is the target which receives the request and is invoked to do the processing of the request. To implement different ways of possible targets the <code>RestRoute</code> interface should be implemented. The most common way of a target is to invoke a method of a class. For this the <code>webservices.rest.routing.RestMethodRoute</code> is implemented which will get the method to invoke.
## Routing arguments

When building the routing table by the <code>RestRouter</code> and filling up with <code>RestRoutingItems</code> the arguments which should be passed to the <code>RestRoute</code> will also be gathered into a <code>RestRoutingArgs</code> object.

This object contains the meta information for each argument. It contains the name of the argument, the data type of the argument and the kind of argument (passed or injected argument).
## Route processing

Finally, when a route was found for a given request, the route should be processed. This is handled by the <code>webservices.rest.server.routing.RestRoutingProcessor</code>. This processor takes care about handling the request and providing the correct information and parameters for the routing target which should be processed (e.g. invoke a RestMethodRoute with the correct arguments or parameters).

When invoking the target the arguments were prepared in front of the invocation to be able to pass the requested data to the target. The <code>RestRoutingArgs</code> object will be used to retrieve the information about the arguments required for the target and a <code>webservices.rest.server.RestDataCaster</code> is used to convert the parameters into the correct format - at least it tries it best to convert it.

In case everything went well, it will invoke the method.
## Data caster

The <code>webservices.rest.server.RestDataCaster</code> is used to convert the request's parameters into the type of the parameter required by the target. It implements a kind of <tt>serialize</tt> and <tt>unserialize</tt> function to convert the data into different types.

The following types will be supported:
- scalar values (<tt>integer</tt>, <tt>string</tt>, ... ) - the standard types of PHP
- stdclass - The PHP's standard classes
- primitives - the XP Framework's <code>lang.Primitives</code> wrappers
- XP types - the XP Framework's <code>lang.types.*</code> wrapper types
- hash maps - the XP Framework's <code>util.Hashmap</code>

When converting a value having child data (e.g. array) the <code>RestDataCaster</tt> will try to convert the values recursively.
## Requests and responses

When transferring data from client to server or vice versa there should be a standard how to encode the data. Usually a REST implementation should support JSON and XML. In the first step only JSON will be supported.

In what way the data is encoded is determied by the <tt>Content-Type</tt> header of the HTTP request (e.g. <tt>application/json</tt>), and the way how the response data is encoded should be specified by the <tt>Accept</tt> header.

The request and response object will be created in the first step of the request processing the in the <tt>RestHttpScriptlet</tt>. This will create adapter classes for the different encodings supported for the request and response which implements the <code>webservices.rest.server.transport.HttpRequestAdapter</code> and <code>webservices.rest.server.transport.HttpResponseAdapter</code> interfaces which provides basic access to request and response properties - for JSON there will be a <code>JsonHttpRequestAdapter</code> and <code>JsonHttpResponseAdapter</code>.
# Security considerations

n/a
# Speed impact

None.
# Dependencies

n/a
# Related documents

xp-framework/xp-framework#67 - origin

**Comment by thekid** [comment]
@ohinckel: As discussed with @mrosoiu and @kiesel, please change `webservices.rest` to `webservices.rest.rpc` or `webservices.rest.server` to be consistens with `webservices.soap` (client) and `webservices.soap.rpc` (server), then I think we're ready to go!

**Comment by ohinckel** [comment]
I moved the implementation into <code>webservices.rest.server</code>.

**Comment by thekid** [comment]
+1 => I'd say commit this!

**Comment by kiesel** [comment]
Let's get this in, +1.

**Comment by thekid** [comment]
Committed in xp-framework/xp-framework@b54a735c6a
