### ISSUE TITLE
Parameter annotations

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#218]
# Scope of Change

Annotations on method parameters will be allowed.
# Rationale

Originally motivated from [XP Framework's pull request #33](https://github.com/xp-framework/xp-framework/pull/33/files) - Stubbles IoC container and dependency injection.
# Functionality

Influenced by syntax discussion in xp-framework/xp-framework#116
## Syntax

While the original idea was to add `/*[@inject(name= 'db')]*/` in front of the parameter inside the declaration, it was decided for visual reasons and being inspired by C#'s attribute targets (see  http://msdn.microsoft.com/library/z0w1kczw.aspx) to use the following form:

``` php
<?php
  class Example extends Object {

    #[@$conn: inject(name= 'db')[
    public function setConnection(DBConnection $conn)  {
      // ...
    }
  }
?>
```
## Reflection

The `lang.reflect.Parameter` class will be extended by the following methods:

``` groovy
  public bool hasAnnotation(string $name, [string $key= null])
  public var getAnnotation(string $name, [string $key= null]) throws lang.ElementNotFoundException
  public bool hasAnnotations()
  public var[] getAnnotations()
```
# Security considerations

n/a
# Speed impact

Slower as method signatures need to be parsed, too.
# Dependencies

**This adds `$details[DETAILS_TARGET_ANNO]` to the class meta information. It contains annotations with targets.** Parameter annotation are just special targets whose name matches the parameter name (including the `$`).
# Related documents

xp-framework/xp-framework#33

**Comment by mikey179** [comment]
I guess you already parse the method signature for reflection purposes? So why not simply use the existing mechanism and add some syntactical sugar to annotations:

```
#[@inject]
#[@named{configPath}('Myapp.config.path')]
__construct(Processor $proc, Request $req, $configPath)
```

In this example the `@named` would only mark the `$configPath` parameter. This way the method signature parsing does not have to be changed, only the annotation parsing would have to be extended. Just some thoughts, don't know whether this is feasible. Main drawback is that the annotation is not directly at the parameter which it annotates and that the parameter name has to be written twice.

**Comment by thekid** [comment]
And this would be added to XP 5.8-SERIES to be forward-compatible:

``` diff
diff --git a/core/src/main/php/lang/XPClass.class.php b/core/src/main/php/lang/XPClass.class.
index 0b43452..b9dcebc 100644
--- a/core/src/main/php/lang/XPClass.class.php
+++ b/core/src/main/php/lang/XPClass.class.php
@@ -18,6 +18,7 @@
   define('DETAIL_THROWS',         3);
   define('DETAIL_COMMENT',        4);
   define('DETAIL_ANNOTATIONS',    5);
+  define('DETAIL_TARGET_ANNO',    6);
   define('DETAIL_NAME',           6);
   define('DETAIL_GENERIC',        7);
```

_Update (Sun Sep 30 13:44:13     2012): DONE._

**Comment by thekid** [comment]
Parameter annotations can already be used today, although they need to be queried via the reflected method:

``` php
<?php
  class Test extends Object {

    #[
    #  @webmethod(verb= 'PUT', path= '/item/{id}'),
    #  @$identifier: path('id'),
    #  @$data: payload,
    #  @$ref: header('X-Reference-Number')
    #]
    public static function main($args) {
      Console::writeLine(create(new XPClass(__CLASS__))->getMethod('main')->getAnnotation($args[0]));
    }
  }
?>
```

``` sh
$ xp Test '$identifier: path'
id
```

...and in an API-compatible way by using https://github.com/thekid/xp-framework/compare/rfc218-fc (although that only _adds_ the annotation methods to the `Parameter` class and doesn't change the `Routine` reflection, which contains `$identifier: path` annotations - remember: extension methods can only "jump in" for non-existant methods, they cannot overwrite functionality!).

**Comment by thekid** [comment]
http://news.planet-xp.net/article/480/2012/09/30/Parameter_annotations
