### ISSUE TITLE
Modules - Classpath meta information & initializers

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#220]
# Scope of Change

Every class path element will be able to provide a way to provide meta information. When it does so, we will call this class path element **a module**. Modules are named, may have a version, are accessible by reflection, annotatable and may contain static initializer blocks.
# Rationale

Prerequisite for XP Framework Modularization - see RFC #204.
# Functionality

If a classpath element (a path or a XAR file) contains a file named `module.xp`, then it is loaded and initialized. For each loaded module, a `lang.Module` instance is created to access the module's meta data and wrap around the class loader for the specific classpath element.
## The "core" module

The XP Framework's core will be represented by a module named `core`.
## Reflection

Here's the `lang.Module` class.

``` php
public class lang.Module extends lang.Object implements lang.IClassLoader {
  protected var lang.Module::$loader
  protected var lang.Module::$definition
  protected var lang.Module::$name
  protected var lang.Module::$version

  public lang.Module __construct(lang.IClassLoader $loader, lang.XPClass $definition, [string $name= null], [string $version= null])

  public static lang.reflect.Module forName(string $name) throws lang.ElementNotFoundException
  public static lang.reflect.Module[] getModules()

  public bool providesClass(string $class)
  public bool providesResource(string $filename)
  public bool providesPackage(string $package)
  public string[] packageContents(string $package)
  public lang.XPClass loadClass(string $class) throws lang.ClassNotFoundException
  public string loadClass0(string $class) throws lang.ClassNotFoundException
  public string getResource(string $string) throws lang.ElementNotFoundException
  public io.Stream getResourceAsStream(string $string) throws lang.ElementNotFoundException
  public string getName()
  public string getVersion()
  public string getComment()
  public bool hasAnnotation(string $name, [string $key= null])
  public var getAnnotation(string $name, [string $key= null]) throws lang.ElementNotFoundException
  public bool hasAnnotations()
  public var[] getAnnotations()
  public lang.IClassLoader getClassLoader()
  public bool equals(var $cmp)
  public string toString([string $cwd= null])
  public string hashCode()
  public string getClassName()
  public lang.XPClass getClass()
}
```
## Example module.xp

``` php
<?php
/* This file is part of the XP framework
 *
 * $Id$
 */

  uses(...);

  /**
   * The example module
   *
   * @see http://example.com
   */
  module example(1.0.0) {
    // Class body here
  }
?>
```
## Restrictions
- Module names must match the following regular expression: `/[a-z][a-z0-9_\/\.-]*/` (all-lowercase, start with an alpha char, and continue with any alphanumeric, underscore, forward slash, dot, or dash). It is recommended to use the pattern `[vendor] "/" [name]` in order to easily integrate with [Composer](http://getcomposer.org/)
- Module versions may contain anything except these special chars: `(`, `)`, `*`, `+`, `-`, `<`, `>`, `[`, `]`, `,` and the combination `..`, although it is highly recommended to stick to [what PHP's version_compare() understands](http://php3.de/version_compare).
## Usecase: Database drivers

Database drivers can be modularized as follows when this RFC is implemented:

**/path/to/sybase_ct/src/main/php/module.xp**:

``` php
<?php
  uses('rdbms.DriverManager');

  module sybase_ct(1.0.3) {
    public static function initialize(IClassLoader $l) {
      DriverManager::register('sybase', $l->loadClass('rdbms.sybase.SybaseConnection'));
    }
  }
?>
```

**/path/to/sybase_ct/src/main/php/rdbms/sybase/**:

```
* SybaseConnection.class.php
* SybaseResultSet.class.php
* SybaseDialect.class.php
```

In the application's class path, we can include `/path/to/sybase_ct/src/main/php/` and will automatically have the `sybase` driver registered.
## Usecase: IoC

IoC containers need a place where the wiring takes place. This can now be done in the static initializer of a module:

**/path/to/app/src/main/php/module.xp**:

``` php
<?php
  uses('ioc.Binder');

  module company/db-app {
    static function __static() {
      with ($binder= new Binder()); {
        $binder->bind('rdbms.DBConnection')->named('lsd')->to(DriverManager::getConnection('...'));
      }
    }
  }
?>
```

**/path/to/app/src/main/php/com/example/scriptlet/state:**

```
* HomeState.class.php
* ...
```

Later on, we can use:

``` php
<?php
  class HomeState extends AbstractState {

    #[@inject, @named('lsd')]
    public function setConnection(DBConnection $conn) { ... }

    public function process($request, $response, $context) { ... }
  }
?>
```

...and have the database connection injected.
# Security considerations

n/a
# Speed impact

Slightly slower because loading a class path will add an addition `stat()` call.
## Class loading optimization

Not all modules need to be searched for all classes, resources or packages. Modules can optionally declare packages they provide, making the class loading mechanism skip them during class lookup based on string comparisons rather than filesystem lookups.

``` php
<?php
  module imaging.test(3.4.1) provides imaging.tests.unittest, imaging.tests.integration {

  }
?>
```
# Dependencies

None.
# Related documents

RFC #0204
http://effbot.org/pyfaq/what-is-init-py-used-for.htm

**Comment by mikey179** [comment]
I don't think the IoC part can work that way, for some reasons:
1. You would have one binder instance per module, but you need to have one binder instance per application, as the bindings are stored in an index which is used to wire the whole application. The bindings defined in the module example above would not be added to this index. How would you solve that?
2. All bindings of a module would have to go there, even if they don't fit together logically. It's rather preferable two have as much instances of `ioc.module.BindingModule` as necessary.
3. Provided the bindings get added to the application's binding index: Declare bindings in such a way means no possibility to configure those within the application's bootstrap part. What you want is to provide configurable binding modules which in turn may have the possibility to influence what will be bound. Aside from missing configuration options the user would have to stick with these predefined bindings, if he wants them or not.

The only way the IoC usecase may provide additional usage is that those define default bindings which are used if no other explicit bindings are defined. However, you are already able to annotate classes or interfaces inside the module with the `@implementedBy` or `@providedBy` annotations which are evaluated if no explicit bindings exist.

**Comment by thekid** [comment]
@mikey179 - I guess I still don't completely understand your IoC implementation (or maybe even any) then, or maybe I'm confusing your `BindingModule` with the "module" word used here, but I thought the basic concept is:

## A) Wiring

Wiring means binding the interfaces to the implementations that should be used, e.g. the `Session` interface to `RedisSession`, the `DBConnection` named `lsd` to a sybase connection to `carla:1433`. This wiring is done at application startup time and is then available to the entire application. As far as I understand, this is usually done inside the static initializer of the application class.

## B) Instanciation

Objects are no longer instantiated by `new [IMPL]` but instead we need to ask the IoC container for an object by `get [INTERFACE]`.

## C) Injection

Injection is the easiest way for us to receive objects from the container, achieved by annotating constructors or methods with `@inject`. It's a programming usability measure though, as we could also ask the container manually:

``` php
<?php
  // With annotations
  class Example extends Object {
    #[@inject, @named('lsd')]
    public function setConnection(DBConnection $conn) { ... }
  }

  // Without
  class Example extends Object {
    public function setConnection(DBConnection $conn= NULL) {
      if (NULL === $conn) $conn= Binder::get('DBConnection')->named('lsd');
    }
  }
?>
```

If this is correct, I don't see any problem if the application defines its module and therein does the wiring. Of course, the application object should also be bound from there, e.g. `$binder->bind('WebApplication')->to(XPClass::forName('com.example.my.Application'))` as the last statement. This is roughly the same as putting the wiring logic in the static initializer of the application class, only that the same class can be reused in a different setup with different bindings.

If you then later on add other class path elements and they want to bind stuff themselves, yes, then you're right, this is tough, because you need to find the binder again (solveable) and have to bind in the correct order (difficult). How is this done in other places?

**Comment by mikey179** [comment]
# A) Wiring

So far correct. Maybe I misunderstand your module concept here, but given that any library xar I use in my own application provides it's own `module.xp` there would be some bindings that I don't have influence on in my application?

# B) & C) Instanciation & Injection

You only ask the IoC container if it is really neccessary, it's kind of a last resort. Typically, using injection (as in the first example of C) or injection providers is preferred. If you really have to you ask the `ioc.Injector` - the `ioc.Binder` is only a facade for the wiring phase.

The second example violates any principle you strive to achieve by using the IoC container. :-) It's more this way:

``` php
<?php
  class Example extends Object {
    #[@inject]
    public function __construct(Injector $injector) { $this->injector = $injector; }
    public function doSomething() { $conn = $this->injector->getInstance('DBConnection', 'lsd'); /.../ }
  }
?>
```

Regarding the app server the deployed application has a main entry class. The app server could do something like

``` php
<?php
  App::createInstance('my.application.MainClass')->run();
?>
```

The name of the main class needs be in some kind of manifest, though so that the app server knows it.

**Comment by thekid** [comment]
OK, thanks for clarifying my example! Yes, there may be multiple modules (class path entries), so yes, sure, they could bind stuff too, but you wouldn't do that - you'd only bind in the `module-info.xp` in your application's class path.

**Comment by mikey179** [comment]
Ah, but if it's only for the application, shouldn't it contain only code required to instantiate the application then? I think binding doesn't belong into this territory and it could be mistaken by library writers if there is the possibility to put the bindings there. The bindings are an important part of an application, and they should use the same techniques available to the other parts of the application - it's even best to have unit tests for those as you have for the other application code.

**Comment by thekid** [comment]
Using `module.xp` as the filename will lead to more special-case handling in the XP compiler which scans through a source path using `*.xp,*.php` as mask. The file `module.xp` is not in XP Language syntax, though, and needs to be excluded.

Because the same goes for `package-info.xp` it seems like an "OK" thing to do.

**Comment by thekid** [comment]
Added version as optional atttribute to this RFC, both of the following are now allowed:

**Versioned module**

``` php
  module imaging(3.4.1) {

  }

  $v= Module::forName('imaging')->getVersion();  // "3.4.1"
```

**Unversioned module**

``` php
  module forkqueue {

  }

  $v= Module::forName('forkqueue')->getVersion();  // NULL
```

[Implementing patch](https://github.com/thekid/xp-framework/compare/045154ded4b9f09ca7d7563a346b77c95ba2617f...605905ac86115f5c44c7f405c09b346899f6eb39) added to pull request xp-framework/xp-framework#219

**Comment by thekid** [comment]
Interesting reads from the Groovy universe:
- http://groovy.codehaus.org/Groovy+2.0+modularization
- http://docs.codehaus.org/display/GROOVY/Creating+an+extension+module

**Comment by mrosoiu** [comment]
Aside from the initialization part, I don't really understand the advantage for adding meta information for modules via `module.xp`. Sure, it's cool to question a module via reflection, but I don't really see a use case here.

The initialization part can be achieved with something faster and simpler like `include()` any `__init__.php` (similar to python) found in any of the registered classpaths.

Maybe this is something tailored for Composer, which I should really take a look at :)

**Comment by thekid** [comment]
Yes, basically it its `__init__.php` inside a classpath, but in the same way we don't support running `script.php` with XP (but instead always run classes with a `main()` method), we here also require classes as initializers.

The reflection part comes with this at almost no cost since we register the module as classloader inside XP's class path. You can see the information in `xp -v`'s output:

``` sh
$ xp -v
XP 5.9.0-dev { PHP 5.4.8 & ZE 2.4.0 } @ Windows NT DWKA-2KVDZ4J 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586
Copyright (c) 2001-2013 the XP group
FileSystemCL<...\xp\core\src\main\php\>
FileSystemCL<...\xp\core\src\test\php\>
FileSystemCL<...\xp\core\src\test\resources\>
FileSystemCL<...\xp\tools\src\main\php\>
lang.Module<xp-forge/jira-api:1.0.1, FileSystemCL<...\vendor\xp-forge\jira-api\src\main\php\>>
FileSystemCL<D:\cygwin\home\friebe\>
```

**Comment by thekid** [comment]
Here's how it looks now after the first separated part was turned into a module:

``` sh
$ xp -v
XP 5.9.0-dev { PHP 5.5.0alpha3 & ZE 2.5.0-dev } @ Windows NT LWKA-BN286R1 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586
Copyright (c) 2001-2013 the XP group
FileSystemCL<C:\...\xp.public\core\src\main\php\>
FileSystemCL<C:\...\xp.public\core\src\test\php\>
FileSystemCL<C:\...\xp.public\core\src\test\resources\>
Module<xp-framework/compiler:1.9.0-dev, FileSystemCL<C:\...\xp.lang\compiler\src\main\php\>>
Module<xp-framework/compiler.test:1.9.0-dev, FileSystemCL<C:\...\xp.lang\compiler\src\test\php\>>
FileSystemCL<C:\cygwin\home\friebe\>
```

**Comment by thekid** [comment]
See also xp-framework/xp-framework#231

**Comment by thekid** [comment]
Reimplemented in current XP6
- Initial implementation (declaration only!) xp-framework/core@3758e4e9eaf5e8c5e76737ea2d21242ef9f81b78
- Tests xp-framework/core@f3c4b5fa6782681c8d9db6ead1ad5149cb312fe6

**Comment by thekid** [comment]
Example usecase: RAD mode -> https://github.com/xp-framework/rad/blob/master/src/main/php/module.xp
