### ISSUE TITLE
Allow combining application properties from multiple sources

### ISSUE THREAD

**Issue by kiesel** [xp-framework/rfc#221]
# Scope of Change

The util.Properties API will be extended so it is possible to combine multiple Properties objects into one when querying property settings.
# Rationale

Often, settings need to extend or modify a set of basic settings, while overwriting or completeing or resetting values. Two examples for this rationale:
- different web application profiles (dev, qa, prod) usually share most data, except connection DSNs and log settings.
- an application could choose to inherit database DSNs settings from a global Properties file, so there's no need to duplicate them.
# Functionality
- A class `util.CompositeProperties` will be introduced which allows combining multiple `util.Properties` to be grouped together and used "as one". Also, the interface `util.PropertyAccess` marks classes that serve as source of properties.
- Then, `util.PropertyManager` will be extended so it supports reading and managing property files not from one filesystem location, but from multiple filesystem paths. When `PropertyManager` finds `Properties` in multiple paths, it will return a `CompositeProperties` that groups all found objects.
### A) Precedence

The order of Properties in the Composite define their precedence:

Given these two properties, added to the composite in this order:

```
[section]
key=value
```

and

```
[section]
key=hidden
```

will make `$composite->readString('section', 'key');` return `value`.
### B) Adding properties

When an element is not declared in the property file with higher precedence, the one of remaining property files containing it will deliver the value:

Given these two properties, added to the composite in this order:

```
[section]
some=value
```

and

```
[section]
key=hidden
```

will make `$composite->readString('section', 'key');` return `hidden`.
### C) Changing values

Changing values is _NOT_ supported. Especially it is not possible to add new values to arrays or hashmaps - even when they are defined with separate property lines:

Given these two properties, added to the composite in this order:

```
[section]
array="one|two"
```

and

```
[section]
array[]="three"
```

will make `$composite->readArray('section', 'array');` return `array('one', 'two')`. The other value is not taken into consideration.
### D) Iterating

`util.Properties` used to provide iteration support through `getFirstSection()` and `getNextSection()` - the new `util.PropertyAccess` interface also supports this.

Given these two properties, added to the composite in this order:

```
[section]
key="value"
```

and

```
[another]
key="value"

[section]
key="some"
```

will make `$composite->getFirstSection()` return `"section"`, then two subsequent calls to `getNextSection()` will yield `"another"`, then `NULL`. Iteration, thus, traverses all unique sections of all properties.
### E) Writing

The `CompositeProperties` implements `util.PropertyAccess` which only support accessing property settings read only. There is no writing support.
# Security considerations

n/a
# Speed impact

`util.PropertyManager` will be affected:
- `hasProperties()` will become slower in worst case, because it will have to search all paths. In best case, the `Properties` object is in first path element, then no impact is expected.
- `getProperties()` will become slower in general, as it has to search all path elements for properties in any case.

The overall performance impact is expected to be negligible, though.
# Dependencies

n/a
# Related documents

**Comment by thekid** [comment]
@kiesel, please add some descriptive text on how property file "inheritance, completing and overwriting" of values works. Maybe an example would help.

**Comment by kiesel** [comment]
I have completed the RFC with some examples.

**Comment by thekid** [comment]
+1
