### ISSUE TITLE
Optional support for PHP 5.3 namespaces

### ISSUE THREAD

**Issue by kiesel** [xp-framework/rfc#222]
# Scope of Change

Support for writing and using classes within PHP 5.3 namespaces will be added to the XP Framework's core. Because PHP namespaces are only available with PHP >= 5.3.0, support will be optional - using XP with PHP 5.2.x just will not offer the feature.
# Rationale

Add benefit of using namespaces in classes. Namespaces allow reusing class names in a separate context, removing the need of class name prefixes and thus increasing overall code readability.
# Functionality

Today, so-called fully qualified classes can be declared as

``` php
<?php
  $package= 'net.xp_framework.example';

  uses('util.Date');

  class net·xp_framework·example·ExampleClass extends Object {
  }
?>
```

Real namespace classes can be constructed like this:

``` php
<?php
  namespace net\xp_framework\example;

  use util\Date;

  class ExampleClass extends \lang\Object {
  }
?>
```

Note how in the second example we have also replaced the `uses()` call with `use`.
# Security considerations

n/a
# Speed impact

n/a
# Dependencies
- Namespace support is only available with PHP >= 5.3.0
# Related documents

Original issue: xp-framework/xp-framework#22
http://de3.php.net/namespaces

**Comment by thekid** [comment]
One thing to note is that `serialize()` format used e.g. in sessioning has changed between PHP 5.2 and PHP 5.3 if the latter is used with namespaces. This creates an upgrading nightmare because all applications relying on a certain session format need to either change in the same instant or to receive forward-compatible pieces of code.

E.g., a lang.Object serialized with PHP 5.3 and namespaces looks like this:

```
string(23) "O:11:"lang\Object":0:{}"
```

PHP 5.2 cannot unserialize this data, returning `FALSE` and issuing a `"unserialize(): Error at offset 0 of 37 bytes"` warning. 

This might need to be addressed by introducing a serialization API **before 5.9** - e.g. xp-framework/rfc#6

**Comment by thekid** [comment]
Being able to use the XP Framework's unqualified classes fully qualified (e.g. `use util\Date`) is achieved via an autoloading implementation and `class_alias()`. A "we said so" note: Classes may of course also be used unqualified for the time being (e.g. `\Object`). Doing so cannot be prevented technically but will cause an upgrade nightmare in the future. **Always fully qualify class names within namespaced classes!**

**Comment by thekid** [comment]
The `ConvertToNamespaces` utility from the commits above can be used to convert an entire directory of PHP sourcecode conveniently:

``` sh
# Transform
$ xpcli ConvertToNamespaces src src-ns
io.collections.iterate.FilteredIOCollectionIterator<io.collections.FileCollection(.\src\)(R)>@{
  io.collections.iterate.ExtensionEqualsFilter(".class.php")
}
[....................................]

# Compare
$ diff -ur src src-ns

# Merge
$ cd src-ns/ && tar cf - . | (cd ../src && tar xf -) ; cd .. ; rm -rf src-ns

# Commit
$ (...)
```

Done!

**Comment by thekid** [comment]
There's some pitfalls with namespaces maybe worth noting (_not related to the XP Framework's implementation_):

## Relative namespaces

The worst thing about PHP namespaces is not the ugly backslash used as separator, but the relative syntax.

``` php
<?php
  namespace de\thekid;

  use util\Date;         // Refers to util\Date - may not include a "\" in front

  class Factory extends \lang\Object {         // Refers to lang\Object - needs add a "\" in front

    public function create($name) {
      switch ($name) {
        case '...': return new impl\DefaultImpl();  // Refers to de\thekid\impl\DefaultImpl!
      }
    }
  }
?>
```

To remember: **Always use absolute syntax except inside `use`**.

## Catch

The `catch` statement doesn't verify the class exists, so the following **will not catch any exception** (as long as `ClassNotFoundException` is not inside `de\thekid`):

``` php
<?php
  namespace de\thekid;

  // ...
  try {
    $cl->loadClass($name);
  } catch (ClassNotFoundException $e) {
    // ...    
  }
?>
```

We should be using `\lang\ClassNotFoundException` or importing it via `use`.

## Type hints

A similar thing happens with typehints. The following will raise a `lang.IllegalArgumentException` that the argument is of incorrect type:

``` php
<?php
  namespace de\thekid;

  // ...
  function handle(XPClass $class) {
    // ...
  }

  handle($cl->loadClass($name));
?>
```

We should be using `\lang\XPClass` here or importing it via `use`.

## Constants

Namespaces may have constants, global constants like `DIRECTORY_SEPARATOR` need to be prefixed with a leading backslash! 

If not prefixed, a [fallback](http://de3.php.net/manual/en/language.namespaces.fallback.php) will occur and will find the correct constants **but will create a noticeable performance decrease** (~ factor 3)

**Comment by thekid** [comment]
Set status to accepted as this is going to the _xp5_9_ branch only and there won't be a release for quite a while there, we have some time to give this some real life exposure.
