### ISSUE TITLE
Rename xp.contrib's "ecma" to "teamcall"

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#223]
# Scope of Change

The "ecma" module should be named "teamcall" after its purpose. 
# Rationale

It should not be named after the ECMA standards it's related to (ECMA is a big standards organization far better known for their ECMAScript - this would be like naming something "DIN" or "ISO").
# Functionality

The `ecma` directory will be moved to `teamcall` in the xp.contrib repository. Any corresponding references in other files will be changed accordingly
# Security considerations

n/a
# Speed impact

n/a
# Dependencies

n/a
# Related documents

See RFC #210

**Comment by kiesel** [comment]
+1

**Comment by thekid** [comment]
Now at https://github.com/xp-forge/teamcall
