### ISSUE TITLE
Rename xp.contrib's "google" to "google-search"

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#224]
# Scope of Change

The "google" module should be named "google-search" after its purpose. 
# Rationale

There's more than just google search APIs out there. This package concentrates on exactly these, though, and not on - for example - the Google+ API.
# Functionality

The `google` directory will be moved to `google-search` in the xp.contrib repository. Any corresponding references in other files will be changed accordingly
# Security considerations

n/a
# Speed impact

n/a
# Dependencies

n/a
# Related documents

See RFC #210

**Comment by kiesel** [comment]
Does google still offer the SOAP implementation? Question is if we should not completely remove it...

**Comment by thekid** [comment]
This package no longer includes the SOAP implementation, only the new REST API, see version 3.0.0 in the ChangeLog:
- Initial release 2004-01-30 = 1.0.0 @thekid 
- xml.soap.Parameter instead of deprecated SOAPNamedItem, 2004-07-02, 1.0.1 @thekid
- QA-Release 2005-04-12 = 1.0.2 @thekid 
- QA-Release 2005-07-25 = 1.0.3 @thekid 
- Bugfix for exception name, 2006-07-11 = 1.0.4 @thekid 
- 2.0.0 for PHP 5 migration @kiesel 
- 2.1.0 for new SOAP API, 2007-04-17 @kiesel 
- QA-Release 2009-06-07 = 2.1.1 @thekid 
- _Deprecated SOAP classes and new search REST services, 2010-04-25, 3.0.0_ @thekid
- New Unmarshaller, 2010-08-22, 3.1.0 @thekid 
- Feature release: spelling, synonyms, key matches, for GSA 2010-12-08, 3.1.1 @thekid
- New details element, 2011-01-24, 3.1.2 @thekid

**Comment by thekid** [comment]
Now at https://github.com/xp-forge/google-search
