### ISSUE TITLE
Rename xp.contrib's "microsoft" to "ms-com"

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#225]
# Scope of Change

The "microsoft" module should be named "ms-com" after its purpose. 
# Rationale

It should no be named after the company Microsoft which provides a variety of APIs.
# Functionality

The `microsoft` directory will be moved to `ms-com` in the xp.contrib repository. Any corresponding references in other files will be changed accordingly
# Security considerations

n/a
# Speed impact

n/a
# Dependencies

n/a
# Related documents

See RFC #210

**Comment by kiesel** [comment]
+1

**Comment by thekid** [comment]
Now at https://github.com/xp-forge/ms-com
