### ISSUE TITLE
Rename xp.contrib's "xmlrpc" to "metaweblog"

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#226]
# Scope of Change

The "xmlrpc" module should be named "metaweblog" after its purpose. 
# Rationale

This might be confused with the XMLRPC communication standard which is supported by the framework's `webservices.xmlrpc` package.
# Functionality

The `xmlrpc` directory will be moved to `metaweblog` in the xp.contrib repository. Any corresponding references in other files will be changed accordingly
# Security considerations

n/a
# Speed impact

n/a
# Dependencies

n/a
# Related documents

See RFC #210

**Comment by ppetermann** [comment]
+1

**Comment by kiesel** [comment]
+1
