### ISSUE TITLE
Remove xp.contrib's "ajp" module

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#227]
# Scope of Change

The "ajp" module will be removed.
# Rationale

It has never seen a productive release. The history is:
- First implementation for AJP 1.3 2003-01-31 = 0.0.1 @thekid
- Migrate to PHP 5 = 0.0.2 @kiesel
- QA-Release 2009-06-07 = 0.0.3 @thekid
# Functionality

The `ajp` directory will be removed from the xp.contrib repository
# Security considerations

n/a
# Speed impact

n/a
# Dependencies

n/a
# Related documents

RFC #210

**Comment by kiesel** [comment]
+1
