### ISSUE TITLE
Rename xp.contrib's "cyrus" to "cyrus-admin"

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#228]
# Scope of Change

The "cyrus" module should be named "cyrus-admin" after its purpose. 
# Rationale

Clarify the real purpose and the module's focus.
# Functionality

The `cyrus` directory will be moved to `cyrus-admin` in the xp.contrib repository. Any corresponding references in other files will be changed accordingly
# Security considerations

n/a
# Speed impact

n/a
# Dependencies

n/a
# Related documents

See RFC #210

**Comment by kiesel** [comment]
+1

I use this in one proprietary project, so I could add the code there and remove this code here - it's not a full implementation of the admin commands of Cyrus, but very incomplete - I only implemented what was required for that project.
