### ISSUE TITLE
Rename xp.contrib's "imc" to "vformat"

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#230]
# Scope of Change

The "imc" module should be named "vformat" after its purpose. 
# Rationale

IMC - the Internet Mail Consortium (http://imc.org/) has many standards. VCard and VCalender, which is what this API provides, are only a small amount of them, but this is what the package focusses on providing.
# Functionality

The `imc` directory will be moved to `vformat` in the xp.contrib repository. Any corresponding references in other files will be changed accordingly
# Security considerations

n/a
# Speed impact

n/a
# Dependencies

n/a
# Related documents

See RFC #210

**Comment by kiesel** [comment]
+1
