### ISSUE TITLE
Remove xp.contrib's "dba" module

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#231]
# Scope of Change

The module "dba" will be completely removed.
# Rationale

The `io.dba` classes where deprecated in the 5.8-SERIES and moved to the `ports` repository (what is now "xp.contrib") for backwards compatibility on  2010-02-14, almost two years ago at the time of writing.
# Functionality

The "dba" directory will be removed from the xp.contrib repository.
# Security considerations

n/a
# Speed impact

n/a
# Dependencies

n/a
# Related documents

See RFC #210

**Comment by thekid** [comment]
Originally announced in http://releases.xp-framework.net/xml/roadmap?5.8.0#Deprecation

**Comment by thekid** [comment]
Announced in http://news.planet-xp.net/article/437/2012/01/22/

**Comment by thekid** [comment]
@kiesel - your vote?

**Comment by kiesel** [comment]
+1 :)

**Comment by thekid** [comment]
Set to accepted.
