### ISSUE TITLE
xp -w and xp -d

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#237]
# Scope of Change

Two new command line options will be added to the `xp` runner:
1. `-w` - Use `Console::writeLine()` on the expression
2. `-d` -  Use `var_dump()` on the expression
# Rationale

Users often find themselves typing `xp -e 'Console::writeLine(...);'`. This should be shortened.
# Functionality

The string passed after the command line will be evaluated with `eval()`. The result it returns is displayed using the selected method.

``` sh
$ xp -w 'return 1 + 2;'
3
```

Because the `return` statement and the trailing semicolon are obvious in this case, it may be omitted:

``` sh
$ xp -w '1 + 2'
3
```

_Note: Internally, if `return` is not contained inside the given sourcecode, it is prepended._

Last but not least, piping source is allowed:

``` sh
$ echo 1 + 2 | xp -w
3
```
# Security considerations
# Speed impact
# Dependencies
1. A new class in xp.core: `xp.runtime.Dump` **[Done]**
2. Patch to the Windows runner sources. **[Done]**
3. Patch to the Un_x runner sources. *_[Done]**
4. Add patch to support piping from STDIN for `xp -e` **[Done]**
# Related documents

**Comment by thekid** [comment]
NodeJS has `-p | --print: print result of --eval`:

``` sh
$ node -p -e '1 + 2'
3
```

Should we maybe align with this ad change the `-w` and `-d` options to work in conjunction with `-e`?

**Comment by kiesel** [comment]
+1

**Comment by iigorr** [comment]
+1

**Comment by srogin** [comment]
I'm not sure I understand the question. Do you mean for -w and -d to only work when using -e?

**Comment by thekid** [comment]
@srogin - this would mean you'd have to write `xp -w -e '1 + 2'` and `xp -d -e '1 + 2'`.

**Comment by srogin** [comment]
Right. Sounds cool :) Anyways, the feature itself is great!

**Comment by thekid** [comment]
Set status to accepted. Targetting at 5.8.4-RELEASE.

**Comment by kiesel** [comment]
Hrm, because this new switch will be added to the runners, which are XP framework version agnostic, this will lead to ClassNotFoundExceptions when using it with older framework versions, right?

Just saying - I think it cannot be circumvented.

**Comment by thekid** [comment]
@kiesel - by backporting, we could. Or by distributing the classes inside `xp.runtime` along with the runners (move xp-framework/tools --> xp-runners/tools) - care to write an RFC for this?

**Comment by kiesel** [comment]
When backporting - to how many versions?

Shifting the classes to ship with the runners could potentially just shift the API incompatibility from "command line" to class incompatibility. This sounds even worse to me, so I'd rather leave it as it is.

**Comment by thekid** [comment]
# Backporting

> When backporting - to how many versions?

By backporting I was thinking about distributing patched tools classes for all 5.8-SERIES. So, starting here: http://xp-framework.net/downloads/releases/5.8.0/

## Option 1
- Keep tools.ar and add a **tools-pl1.ar** including the new class alongside. 
- Change the setup routine to check for a file **patches.map** containing something like tools.ar=tools-pl1.ar
- Releases can be upgraded by reinstalling them via the usual `wget ... | php` way.

## Option 2
- Rename tools.ar to tools-orig.ar, and replace tools.ar with new version
- Releases can be upgraded by reinstalling them via the usual `wget ... | php` way.

## Option 3
- Provide patched tools.ar files on GitHub
- Add a Wiki page explaining the upgrade path.

_...and repeat this for all of 5.8.x (if we script it, it could also be done for 5.7)_.

I'm not really happy with this because we're changing once-released versions, although it would solve the problem you're describing.

# Move tools

> Shifting the classes to ship with the runners could potentially just shift the API incompatibility 
> from "command line" to class incompatibility. This sounds even worse to me, so I'd rather leave it as it is.

The question here is whether or not the framework or the runners change in such ways that an incompatiblity would exist (or maybe restricting to a given series).

Let's have an exemplary look some recent / upcoming changes to the runners

## `xcc -e` (xp-framework/rfc#238)

Change can be accomplished by changing the class `xp.compiler.Runner` class inside the `xp.lang` repository. If we wanted to move `xp.compiler.Runner` out of the repository: This class has been changed quite often to adapt new compiler APIs. In order for this class to be a little more "static", we could separate the command line option parsing from the compiler API itself (e.g. instead of `if ('-v' == $args[$i]) { $listener= new VerboseDiagnosticListener(Console::$out); }` we would introduce a new `CompilerOptions` "bridge" object and have `if ('-v' == $args[$i]) { $this->setVerbose(TRUE); }`. And yes, we would then run into the incompatibilities on exactly this object.

## Multiple config paths (xp-framework/xp-framework#118)

Change to scriptlet and command runners, dependant on new `PropertySource` interface and `PropertyManager::appendSource()` introduced inside rfc #221. If we wanted to separate the runners into another repository, we we would run into the problem that they couldn't be version agnostic, requiring us to add checks such as `if (interface_exists('PropertySource', FALSE))` to the sourcecode.

_From just these two examples, looks like this would be the toughest way to go._

# Delay this

By re-targetting this RFC until 5.9, we wouldn't be in this situation, because we define that the series don't have to be compatible.

**Comment by thekid** [comment]
# Conclusion

Thinking about the above options, I currently tend towards **a) implementing now** (this feature is geared towards developers, who will either work with the most current releases or have a checkout) and **b) investigating the backporting option** (in a new RFC, using this here as motivation). If done right and with the correct tooling on both development and user side, this could help in the future, for example also for security-related bugs. 

At the moment, if there was a security bug found, we would probably make releases from all of 5.7, 5.8 and 5.9 series (would currently give us: 5.7.14 and 5.8.4, there is no release to 5.9 at the time of writing). But people on, say, 5.8.1 who cannot upgrade because their code relies on strange behaviour of the `parse_ini_file()` function we switched away from after that release, would be left a bigger problem (_of course, they shouldn't be relying on undocumented features in the first place, but this may have happened unintentionally_).

@kiesel - what's your opinion on this?

**Comment by kiesel** [comment]
I would agree here; though I've come up with the BC issue, I think this is a developer tooling improvement that we should definitively have. I guess, devs usually won't work against a fixed version anyways, so it's ok to create the feature now and elaborate on ways to possibly fix BC later...

**Comment by thekid** [comment]
So I'd say let's get this out into 5.8.4-RELEASE, this will be a chance for people to upgrade their runners.

**Comment by thekid** [comment]
To update runners:

``` sh
thekid@kartofel ~/
$ cd bin

thekid@kartofel ~/bin
$ ./xprt-update.sh
[...]
```

If you haven't updated your XP checkout / fork yet, you should see the error **lang.ClassNotFoundException (Class "xp.runtime.Dump" could not be found)** appearing if you execute `xp -w` or `xp -d`.

**Comment by thekid** [comment]
With XP 5.9, the following is now possible:

``` sh
$ xp -w 'new util\Date()'
2012-02-21 20:43:16+0100
```

_In XP 5.8, this has to read `xp -w 'uses("util.Date"); new Date()'` instead - autoloading comes with namespaces support (see also RFC #222)_
