### ISSUE TITLE
xcc -e and xcc -w

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#238]
# Scope of Change

In conjunction with `xp -e` and `unittest -e`, this RFC proposes to add `xcc -e`.
# Rationale

Support what both of the other runners already do, evaluate sourcecode directly as the fastest way to discover "what something does".
# Functionality

The source code will be compiled and then run. 
## xcc -e

The context is a method declaration. So the following:

``` sh
$ xcc -e xp 'util.cmd.Console::writeLine("Hello");'
Hello
```

... is basically the equivalent of:

``` groovy
public class _Generated {
  public static void main() {
    util.cmd.Console::writeLine("Hello");
  }
}
```

Note: A trailing `;` may be omitted,
## xcc -w

Same as above, but the result of the expression inside the code parameter is written to the console using `Console::writeLine()`.

``` sh
$ xcc -w xp '$args.length' 1 2 3
3
```

Note: The `return` statement as well as trailing `;` may be omitted. If the code contains `return` at any place, no `return` is added up front.
## Languages

All language syntaxes supported by the compiler should be supported.
# Security considerations
# Speed impact
# Dependencies

The command line argument `-e` ("emitter") will be changed to `-E`. Momentarily, this argument can not be in use as there is only one emitter.
# Related documents

**Comment by thekid** [comment]
This of course only works really well for when we emit code that runs on the same platform as the compiler runs... for example, imagine the XP Compiler generating JavaScript - how would `xcc -e` know where to find NodeJS' `node` executable? /cc @iigorr and @kiesel

**Comment by kiesel** [comment]
This feature would be handy.

About the question: it could just assume the executable to be on `$PATH`.

**Comment by thekid** [comment]
Announcement @ http://news.planet-xp.net/article/527/2013/05/12/
