### ISSUE TITLE
Compact method syntax

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#241]
# Scope of Change

A compact syntax for simple methods will be introduced
# Rationale

Slightly less `return $this.member;` typing - especially in value objects.
# Functionality

The `-> expression;` notation is used as a shorthand for `{ return expression; }`.

``` groovy
public class Person {
  protected string $name;

  public string getName() -> $this.name;
}

// Equivalent of
public class Person {
  protected string $name;

  public string getName() {
    return $this.name;
  }
}
```

Combined with the compact assignment syntax described in RFC #240 and the fluent interface shorthand in RFC #252 we can now write value object as follows:

``` groovy
public class Person {
  protected string $name;

  public __construct($this.name= null) { }
  public void setName($this.name) { }
  public this withName($this.name) { }
  public string getName() -> $this.name;
}
```
# Security considerations

n/a
# Speed impact

None, resolved during compile time.
# Dependencies

n/a
# Related documents
- [Dart](http://www.dartlang.org/)'s "`=> e;` shorthand"
- RFC #240 - Compact assignment syntax
- XP Language's anonymous functions use this (slightly different, e.g. in `return #{ $a -> $a + 1 }.(2); // 3` it separates the arguments from the body, but this still has chances for recognition).

**Comment by mrosoiu** [comment]
+1 Cool!

**Comment by thekid** [comment]
After implementing lambda support in thekid/xp-js, I think we should really align their syntax and this one better. Following the idea that `-> X` is a shorthand for `{ return X }`, the long form of lambdas should be changed and the `->` removed from it, as now it feels kind of _duplicate_ here.

## Old form

``` groovy
$func= #{ $a -> $a * $mul };
$func= #{ $a -> { 
  return $a * $mul; 
}};
```

## New form

``` groovy
$func= #{ $a -> $a * $mul };
$func= #{ ($a) { 
  return $a * $mul;
}};
```

...or maybe even omit the enclosing `{}` around the long form:

``` groovy
$func= #{ $a -> $a * $mul };
$func= #($a) { 
  return $a * $mul;
};
```
