### ISSUE TITLE
Method overriding short syntax

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#244]
# Scope of Change

When overriding methods, a shorter syntax will allow omitting modifiers, return type, throws declaration and signature.
# Rationale

Less typing, less to change on refactoring.
# Functionality

Given the following base class:

``` groovy
public class Base {
  public int run(string[] $args) throws IllegalStateException {
    // ...
  }
}
```

The following two are equivalent:

``` groovy
public class Child extends Base {
  public int run(string[] $args) throws IllegalStateException {
    // ...
  }
}
```

``` groovy
public class Child extends Base {
  override run {
    // ...
  }
}
```
# Security considerations
# Speed impact
# Dependencies
# Related documents

**Comment by mrosoiu** [comment]
What about interfaces and `implement`?

``` groovy
interface Interface {
  public int run(string[] $args) throws IllegalStateException;
}
```

``` groovy
public class Class implements Interface {
  implement run {
    // ...
  }
}
```

**Comment by thekid** [comment]
@mrosoiu - yes, this would be nice and consistent.
