### ISSUE TITLE
Plus (+) for string concatenation

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#245]
# Scope of Change

XP Language's concatenation operator `~` will be replaced by an overloaded version of `+`.
# Rationale

Consistency with pretty much every other language.
# Functionality

For the PHP platform, the compiler must detect the string type reliably, as using `+` on strings in PHP converts them to numbers and adds them:

``` sh
$ php -r 'echo "Hello" + "World"'
0
```
# Security considerations
# Speed impact
# Dependencies
# Related documents

http://news.dartlang.org/2012/06/vm-to-remove-support-for-string.html - reasons against doing this

**Comment by mrosoiu** [comment]
+100 :)

**Comment by thekid** [comment]
Added link to Dart Language blog - [VM to remove support for String + operator by June 17th](http://news.dartlang.org/2012/06/vm-to-remove-support-for-string.html) - they suggest to use `StringBuilder` or string interpolation instead
