### ISSUE TITLE
Catch and rethrow

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#246]
# Scope of Change

A short syntax version of catch / rethrow will be introduced and allow to omit the variables.
# Rationale

Less typing.
# Functionality

``` groovy
try {
  // ...
} catch {
  // ...
  throw;
}
```
# Security considerations
# Speed impact
# Dependencies
# Related documents

**Comment by mrosoiu** [comment]
How about `rethrow;`?

Although moving away from the mainstream (C++, C#) is not good...
