### ISSUE TITLE
Named arguments

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#251]
# Scope of Change

Named arguments will be supported.
# Rationale

Enhance readability in certain situations.
# Functionality

The new syntax will be modeled after the map literal, `key : <<expr>>`.
## Example 1: Skipping parameters

Given the following class:

``` groovy
public class HttpConnection {

  public HttpResponse get(string $url= null, [:var] $params= [:], [:var] $headers= [:]) {
    // ...
  }
}
```

**There is no way to skip url and params** - the way to invoke the `get()` method without supplying them but by adding headers is to look at the methods declaration and pass the default values.

The new syntax will allow this, leaving the copy&paste mess to the compiler.

``` groovy
$conn= new HttpConnection();
$response= $conn.get(headers : [ 'Content-Type' : 'application/json']);
```
## Example 2: Clarifying intent

Even when the usecase is not to skip parameters, sometimes a named argument can supply some more information:

``` groovy
new IOCollectionIterator($collection, true);              // Hrm...
new IOCollectionIterator($collection, recursive : true);  // Perfectly clear!
```

As one can see, named and positional parameters can be mixed. However, a positional argument cannot follow a named argument. The following statement causes a compiler error.

``` groovy
new IOCollectionIterator(collection : $collection, true);  // Does not compile
```
# Security considerations
# Speed impact

Compile-time will be slower since heavier lifting is required inside the compiler. There will be no runtime speed impact.
# Dependencies
# Related documents
- http://msdn.microsoft.com/en-us/library/dd264739.aspx - Named and Optional Arguments (C# Programming Guide)
- http://bugs.ruby-lang.org/issues/show/4172 - Ruby feature request
- http://rosettacode.org/wiki/Named_parameters - Overview of tons of languages
- http://www.dartlang.org/language-tour/#functions - Dart (Google's JavaScript competitor) on named and optional arguments

**Comment by mrosoiu** [comment]
+1. I love this!

**Comment by thekid** [comment]
First implementation available @ https://github.com/thekid/xp-language/compare/named-args

**Comment by thekid** [comment]
For the above first implementation, TODO:
- Check parameter names against signature (e.g., invoking `$conn.get()` with `header: ...` instead of `header*s*: ...`).
- Mixing named and positional arguments
- Handle native invocations
