### ISSUE TITLE
Scoped static import

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#253]
# Scope of Change

Scoped imports will be added.
# Rationale

Prevent ambiguities in naming, make name resolution easier for the reader.
# Functionality

The `import` keyword will be recycled to form a block.
## Example

``` groovy
$criteria= new Criteria();
import (rdbms.criterion.Restrictions::*) {
  $criteria.add(in('status', [10000, 20000])).add(equal('author', $author));
}
```

The `in()` and `equal()` invocations will be resolved to the Restrictions' class static methods.
# Security considerations

n/a
# Speed impact

n/a
# Dependencies

n/a
# Related documents

**Comment by thekid** [comment]
Not sure, maybe `with` would look better?

``` groovy
$criteria= new Criteria();
with (rdbms.criterion.Restrictions::*) {
  $criteria.add(in('status', [10000, 20000])).add(equal('author', $author));
}
```

**Comment by mrosoiu** [comment]
I am pretty much against usage of static imports as, in my opinion, it makes the code unreadable / unmaintainable and instead you get just the advantage of typing less.

Scoped static imports make it just a bit more bearable :)

**Comment by thekid** [comment]
Decided against this after rereading.
