### ISSUE TITLE
IoC - Dependency Injection

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#257]
# Scope of Change

A new package `inject` will be added. It will provide the XP Framework's dependency injection API. The `util.cmd.Command` class' `@inject` annotations' terminology will be supported.
# Rationale
# Functionality
## Binding

Values can be bound to the injector by using its addBinding() method. It accepts the type to bind to, an optional name and three different scenarios:
1. Binding an class: The typical usecase, where we bind an interface to its concrete implementation.
2. Binding an instance: By binding a type to an existing instance, we can create a "singleton" model.
3. Binding a Provider: This allows implementing lazy-loading semantics. The provider's get() method will be invoked when a binding is looked up either by an injection or manually via getBinding().
## Instance creation

Keep in mind: "newInstance() is the new 'new'". To create objects and perform injection, use the Injector's newInstance() method instead of using the `new` keyword or factories.

``` php
<?php
  // Old way
  $instance= cast(SessionFactory::getSession(), 'scriptlet.Session');

  // Using the injector
  $instance= $injector->newInstance('scriptlet.Session');
?>
```
## Injection

Injection is performed by looking at a type's constructor, its fields and methods and checking for the `@inject` annotation.

**Constructor**

``` php
<?php
  class ReportImpl extends Object implements Report {
    #[@inject]
    public function __construct(ReportWriter $writer) { ... }
  }
?>
```
## Field

``` php
<?php
  class ReportImpl extends Object implements Report {
    #[@inject, @type = 'ReportWriter']
    public $writer;
  }
 >
```
## Method

``` php
<?php
  class ReportImpl extends Object implements Report {
    #[@inject]
    public function setWriter(ReportWriter $writer) { ... }
  }
?>
```
## Notes

If type hints cannot be used in constructors or methods, `@inject` supports an optional "type" key, e.g. `#[@inject(type = ...)]`. Named instances can be queried by supplying the "name" key, e.g.:

``` php
<?php
  class ReportImpl extends Object implements Report {
    #[@inject(type= 'rdbms.DBConnection', name = 'stats')]
    public function useStatDatabase($conn) { ... }
  }
?>
```
# Security considerations
# Speed impact
# Dependencies
# Related documents
- xp-framework/xp-framework#33: Port of Stubbles IoC to XP (by @mikey179)
- xp-framework/xp-framework#117: ioc.DependencyInjectionContainer (by @mrosoiu)
- https://github.com/thekid/xp-framework/compare/scriptlet-inject (by @thekid)
- RFC #218 - Parameter annotations 
- RFC #220 - Modules using their static initializer to perform wiring discussion
- RFC #24 - ResourceManager - our first idea at something like this
- http://code.google.com/p/google-guice/
- http://google-guice.googlecode.com/files/Guice-Google-IO-2009.pdf
- https://github.com/stubbles/stubbles-core/wiki/Introduction

**Comment by mikey179** [comment]
Why the need for `XPClass` when requesting the instance via `$instance= $injector->newInstance(XPClass::forName('scriptlet.Session'));`? I think that `XPClass` is used here should be hidden, it should be sufficient to just provide the class name.

Is there a good reason to support field injection? It's widely accepted that fields should stay inside the class and the only way to access it should be using methods. If it's for bc reasons only, wouldn't this be a good way to enforce switching away from direct field access?

**Comment by thekid** [comment]
> Why the need for XPClass when requesting the instance 

@mikey179 - Yes, I stumbled upon this too, and should it accept both, a class name and a class object.

**Comment by thekid** [comment]
> Is there a good reason to support field injection?

Hrm, good point. No BC reasons, really. Guess I added it because [Guice has it](http://code.google.com/p/google-guice/wiki/Injections#Field_Injection) - but yes, this could be removed.

**Comment by thekid** [comment]
Implemented by https://github.com/xp-forge/inject/
