### ISSUE TITLE
Multiple resultsets

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#259]
# Scope of Change

Multiple result set support will be added to database connections.
# Rationale

Handle multiple results instead of silently discarding them - e.g. to enable writing generic database clients.
# Functionality
## Current situation

Currently, the way of handling results with `DBConnection`s is as follows:

``` groovy
$conn= DriverManager::getConnection($dsn);
$conn.connect();

// For queries that produce resultsets
$q= $conn.query('select ...');
while ($record= $q.next()) {
  // ...
}

// For queries that don't
$conn.query('update ...');
$affected= $conn.affected();
```

The `query()` method returns `var` - either  `rdbms.ResultSet` or boolean `TRUE` depending on whether the query produces a resultset. If we wanted to handle this generically, e.g. in a database shell / GUI client, we would probably check using `instanceof ResultSet`.
## Idea 1: Change query()

The `query()` method will be changed to return a `rdbms.Result` instance in any case. This class can check whether result sets are available and iterate over them. This creates a BC break, of course. As usually the result of the `query()` method is **not** checked, we should be able to do this without creating major havoc, though. 
## Idea 2: Add execute()

A new method `execute()` would be added. This method would be declared as follows:

``` groovy
public rdbms.Result execute(string $sql, var... $args) throws rdbms.SQLException
```

The `query0()` method would be changed to also always return a `Result` instance. The `query()` method would be changed to the following pseudo-code:

``` groovy
$r= $this.query0($sql);
if ($r.isResult()) {
  return $r.nextResult();
} else {
  return TRUE;  // No resultset produced
}
```
## Results

The `rdbms.Result` class would be defined as follows:

``` groovy
package rdbms;

class Result extends Object {
  public bool isResult() { ... }
  public bool moreResults() { ... }
  public ResultSet nextResult() { ... }
  public int affected() { ... }

  // BC: This can also be used like a ResultSet. This method iterates on
  // the records of the current result set (fetching the first result set if 
  // necessary, and discarding any others). It throws an exception if you 
  // try to fetch records when the query produced no results.
  public [:var] next() throws SQLStateException { ... }
  public void close() { ... }
}
```

_Note: While we're changing this anyway, the `next()` method should return `NULL` instead of `FALSE` to signal completion!_

**Default usage** (unchanged calling code for any of the two above ideas):

``` groovy
$q= $conn.query('select ...');
while ($record= $q.next()) {
  // ...
}
```

**Handling complex results generically** (for idea 2, exchange query() with execute()):

``` groovy
$q= $conn.query('call multiple_results()');
if ($q.isResult()) {
  do {
    $s= $q.nextResult();
    while ($r= $s.next()) {
      // ...
    }
    $s.close();
  } while ($q.moreResults());
} else {
  $affected= $q.affected();
}
```
# Security considerations

n/a
# Speed impact

n/a
# Dependencies
- BC break for query() in idea 1
- New method in base class for idea 2
- BC break for next() - NULL instead of FALSE
# Related documents

See also:
- SQL Server 2012: Handling Complex Statements: http://msdn.microsoft.com/en-us/library/ms378529.aspx

**Comment by mrosoiu** [comment]
I would go for solution 2, without implementing the `Result::next()` method. If you expect one ResultSet or one affected count, then call `DBConnection::query()`; if you expect more ResultSets and/or affected count, then call `DBConnection::execute()`.

One other thing: in the "Handling complex results generically" example, you can have either an `update/insert` statement or more `select` statements; mixing is not possible.

I think something along this lines allows both:

``` php
package rdbms;

class Result extends Object {
  public bool hasMoreResults() { ... }

  // Advances to next result.
  // Returns true if the current result is a result set. Otherwise, false
  public boolean nextResult() { ... }

  // Can be called only if nextResult() returned true
  // Alternate name: getResultSet()
  public ResultSet resultSet() { ... }

  // Can be called only if nextResult() returned false
  // Alternate name: getAffected()
  public int affected() { ... }
}
```

``` php
Result $q= $conn.execute('select...; update...; select...');
while ($q.hasMoreResults()) {

  // Current result is a ResultSet
  if (true === $q.nextResult()) {
    ResultSet $rs= $q.resultSet();
    while ($r= $rs.next()) {
      // ...
    }

  // Current result contains affected rows count
  } else {
    int $affected= $q.affected();
  }
}
```

Also when looking at `Result` and `ResultSet` classes, my first thought is that `ResultSet` is a collection of `Result`. Maybe we can come up with a better name: `QueryResult` or `ExecuteResult`.

**Comment by kiesel** [comment]
I think we should add a new method instead of changing existing ones here - so I vote for idea 2). On the long term the "magic" behaviour from idea 1) would be confusing to new users.

Usually the majority of programs will still just expect an exact amount of result sets and most will expect 1; the others can upgrade to the new method to acquire all of them (this is probably mostly where programs send previously unknown queries - eg. a database shell).
