### ISSUE TITLE
Split up framework into minimal pieces

### ISSUE THREAD

**Issue by kiesel** [xp-framework/rfc#262]
# Scope of Change

The collection of classes delivered with the framework will be shrinked to an absolute minimum. Classes required for bootstrapping and very basic and common operations will be shipped as the "XP Framework Core", others will be available as separate library.
# Rationale

The XP Framework today comes with a collection of standard implementations forming the whole classbase; this includes, for example, `scriptlet` package as the foundation for HTTP processing, `rdbms` to perform database queries, `img` for image manipulation.

While they're very frequently used, they don't form the very base of the framework. Separating them is supposed to support
- implementation variance
- separate release cycles
- shrinking the size of XP applications (only include what's required)
- ...
# Functionality
## Split

The following packages will remain in `core`:
- `lang`
- `io`
- `peer`
- `util`
- `text`, including:
  - `text.encode`
  - `text.format`
  - `text.regex`
  - `text.util`
  - classes `text.CSVGenerator`, `text.StringUtil`

The following packages will become separate modules:
- `gui`
- `img`
- `math`
- `rdbms`
- `remote`
- `scriptlet`
- `security`
- `text.csv`
- `text.doclet`
- `text.parser`
- `text.spelling`
- `unittest`
- `webservices`
- `xml`

Modules provided by the XP Framework as a stable and reliable base continue to be hosted within the XP Framework organisation at GitHub.
## Release

The framework and modules will not share a release cycle; their version numbers, will diverge, consequently. In order make that clear, the following applies to their versioning:
- XP Framework Core will continue to carry its current version number
- all modules will be reset to version 1.0.0
## Dependencies

All modules depend on XP Framework Core, but modules may also depend on another module (such as `webservices`) depend on `xml`. Thus, to efficiently manage this, a dependency management should be used.

Core modules should have no external dependencies - it should be self contained.
# Security considerations
# Speed impact

Speed impact by adding more paths to an `include_path` is expected; if that develops to be grave, effort must be spent to build packaging forms that counterwork that effect (eg. building uber-xars).
# Dependencies
# Related documents
- RFC #172 - XP 6

**Comment by mrosoiu** [comment]
+1 looks good to me

**Comment by kiesel** [comment]
- Changed the versioning of modules & core.

**Comment by iigorr** [comment]
+1

**Comment by thekid** [comment]
As discussed with @kiesel  - let's see if we can somehow manage to make our dependency management solveable by [composer](http://getcomposer.org/)

**Comment by mrosoiu** [comment]
[xp-maven-plugin](https://github.com/xp-forge/xp-maven-plugin) is already able to manage dependencies (actually Maven is doing that):
- you define in pom.xml the direct dependencies that your project relies upon
- when you 'make test', direct and transient dependencies are downloaded into `~/.m2/repository` and an entry for each one is added in the generated `[/path/to/project]/target/project.pth` before executing the unittest runner
- if you 'mvn package -Dxp.package.packDependencies', all dependencies are packed (merged or XAR inside XAR) in the resulting artifact

For local development, we can add a new goal (say 'mvn generate-pth'), that will:
- download all XAR dependencies (direct and transient) to `[/path/to/project]/lib`
- generate/update the `[/path/to/project]/project.pth` file with references to all downloaded dependencies

**Comment by kiesel** [comment]
Dependencies from new core to the rest - needs to be resolved:
- `io.archive.zip.ZipCipher` -> `math.BigInt`
- `peer.mail.InternetAddress` -> `text.encode.QuotedPrintable`
- `peer.mail.InternetAddress` -> `text.encode.Base64`
- `peer.mail.transport.MailTransport` -> `text.encode.QuotedPrintable`
- `util.collections.Queue / Stack` -> `text.String`
- `util.log.LogObserver` -> `rdbms.DBObserver`
- `util.Properties` -> `text.TextTokenizer`
- `util.semaphore.SessionSemaphore` -> `scriptlet.HttpSession`

**Comment by thekid** [comment]
`io.archive` could be extracted into a new module "archives" or even `io.archive.zip` to "zip-archive".

**Comment by thekid** [comment]
The dependency `util.collections.Queue / Stack -> text.String` was a false positive, see xp-framework/xp-framework@8222f1d

**Comment by thekid** [comment]
Maybe the text package should remain in the minimal package except `text.csv`, `text.parser`, `text.doclet` and `text.spelling`, each of which would be extracted into its own module.

``` sh
$ xp -r text
@lang.FileSystemClassLoader<F:\...\xp.public\core\src\main\php\>
package text {
  package text.csv
  package text.doclet
  package text.encode
  package text.format
  package text.parser
  package text.regex
  package text.spelling
  package text.util

  public abstract class text.Tokenizer
  public class text.CSVGenerator
  public class text.Collator
  public class text.DateFormat
  public class text.StreamTokenizer
  public class text.StringTokenizer
  public class text.StringUtil
  public class text.TextTokenizer
}
```

The package `text.util` should go to the `security` package:

``` sh
$ xp -r text.util
@lang.FileSystemClassLoader<F:\...\xp.public\core\src\main\php\>
package text.util {

  public class text.util.RandomCodeGenerator
  public class text.util.RandomPasswordGenerator
}
```

The package `text.format` has been deprecated for a while IIRC.

**Comment by iigorr** [comment]
- util can be decomposed into smaller speciallized packages or at least some aspects should be extracted.
- "extracted" packages should be cut less along technological boundaries but more along logical ones. e.g. LogObserver might just belong in rdbms.log.

**Comment by kiesel** [comment]
Split up `text` package as proposed in @thekid's comment.

**Comment by thekid** [comment]
Oh, and `text.CSVGenerator` (deprecated) and `text.StringUtil` (swiss army knife antipattern) could both be put to rest I think.

**Comment by thekid** [comment]
The resulting filesystem of a development checkout may look as follows:

```
/path/to/xp
^- core     # Minimal framework, maybe named "skeleton"? - from xp-framework/xp-framework
|   ^- boot.pth
|   |- tools [ class.php web.php xar.php lang.base.php ]
|   |- src/main/php [ lang io peer util text xp ]
|   `- src/test/php [ ... ]
|
|- rdbms     # Database drivers - xp-framework/rdbms
|  ^- module.pth
|  |- src/main/php [ sybase mysql mssql pgsql sqlite criteria ]
|  `- src/test/php [ ... ]
|
|- unittest  # Unittest API - xp-framework/unittest
|  ^- module.pth
|  |- src/main/php [ unittest ]
|  `- src/test/php [ ... ]
|
|- scriptlet # Scriptlets (required for "rest" module) - xp-framework/scriptlet
|  ^- module.pth
|  |- src/main/php [ scriptlet ]
|  `- src/test/php [ ... ]
|
|- xml       # XML Support (required for "rest" module) - xp-framework/xml
|  ^- module.pth
|  |- src/main/php [ xml ]
|  `- src/test/php [ ... ]
|
|- rest      # REST Webservices - JSON and XML - xp-framework/rest
|  ^- module.pth
|  |- src/main/php [ webservices.rest webservices.json ]
|  `- src/test/php [ ... ]
|
|- lang      # XP Language - xp-framework/xp-language
|  ^- compiler.pth
|  |- src/main/php [ xp ]
|  `- src/test/php [ ... ]
| 
`- stomp     # STOMP Protocol - xp-forge/stomp
   ^- module.pth
   |- src/main/php [ unittest ]
   `- src/test/php [ ... ]
```

So we'll end up with lots of `use` entries, and then lots of class loaders being registered (16 in the above case, plus `.`).

**Comment by thekid** [comment]
See also xp-framework/xp-framework#231

**Comment by thekid** [comment]
Extracting the unittest module, first try:

``` sh
# Remove everything except unittest relevant
$ git rm -qr .
$ git reset -- src/main/php/unittest/ src/test/php/net/xp_framework/unittest/tests
$ git co -- src/main/php/unittest/ src/test/php/net/xp_framework/unittest/tests
$ git ci -m 'Extract module "unittest"' .
$ git gc --aggressive --prune

# Push to its new location
$ git remote rm origin
$ git remote add origin git@github.com:xp-framework/unittest.git
$ git push origin master
```

Unfortunately, this leaves us the entire history, not just that of the above directories. For that to work, I think we should be using `git filter-branch`; but haven't found out how to do that correctly so far.

**Comment by thekid** [comment]
Extracting the unittest module, second try, based on [this stackoverflow q/a](http://stackoverflow.com/questions/6391103/can-i-completely-remove-the-history-of-all-files-in-selected-subdirs-of-my-repo):

``` sh
# Filter branch
$ git filter-branch -f --index-filter 'git read-tree --empty && git reset -q "${GIT_COMMIT}" -- src/main/php/unittest/ src/test/php/net/xp_framework/unittest/tests'

# Status
$ git st
# On branch master
# Your branch and 'origin/master' have diverged,
# and have 18383 and 18383 different commits each, respectively.
#   (use "git pull" to merge the remote branch into yours)
#
nothing to commit, working directory clean
```

:coffee: Takes forever but output looks good - this'll be our recipe.

**Comment by thekid** [comment]
Scripted solution, taking files with the directories to keep inside as first line as input:

``` sh
#!/bin/sh

if [ "-e" = "$2" ] ; then
  EXEC=
else
  EXEC=echo
fi

# Checkout
if [ ! -f core6-split.tar.gz ] ; then
  $EXEC git clone git@github.com:xp-framework/core.git core6-split
  $EXEC tar cvfz core6-split.tar.gz core6-split/
fi

echo "===> Working on $1"

# Use fresh copy
$EXEC rm -rf core6-split
$EXEC tar xvfz core6-split.tar.gz
$EXEC cd core6-split

# Filter
keep="'git read-tree --empty && git reset -q "${GIT_COMMIT}" -- "`head -1 $1`"'"
$EXEC git filter-branch -f --index-filter $keep

# Remove temporary history git filter-branch leaves behind
$EXEC rm -rf .git/refs/original/
$EXEC git reflog expire --all 
$EXEC git gc --aggressive --prune

# Push to its new location
$EXEC git st
$EXEC git remote rm origin
$EXEC git remote add origin git@github.com:xp-framework/$1.git
$EXEC git push origin master
```

**Comment by thekid** [comment]
:white_check_mark: First module has been extracted - **remote**. 

### Notes:
- The repo was created manually
- We forgot src/test/resources
- The complete history persists and makes it look kind of funny
- The following files should be created: README.md (empty), ChangeLog.md (from a template) and class.pth (containing src/main/php/, src/test/php/ and src/test/resources/)
- Converting to namespaces is `xpcli -cp ../../xp.experiments/ns-convert/ ConvertToNamespaces src/main/php`
- This caused small problems, which needed to be manually fixed (see xp-framework/remote@27db06f)
- We should think about moving the unittests out of `net.xp_framework.unittest` to `remote.unittest`.
- We should add a Travis build
- We need to integrate with the XP Build system by adding the webhook `http://webservices.xp-framework.net/hook` manually.
- At the end, don't forget to remove the remaining files from xp-framework/core - _update: + src/test/config/unittest/$PACKAGE.ini_

See https://github.com/xp-framework/remote.

**Comment by thekid** [comment]
- [x] Added src/test/resources where applicable
- [x] Created [this script](https://gist.github.com/thekid/7400980) for unittest package migration (90%, may need manual afterwork).
- [x] Scripted most of the above notes, to be run after cloning the extracted repository:

``` sh
#!/bin/sh

# Fetch description
MODULE=$(basename "$(realpath .)")
DESC=$(curl https://api.github.com/repos/xp-framework/$MODULE | grep description | cut -d '"' -f 4)
PACKAGE=${1-$MODULE}
echo "===> Working on $MODULE ($PACKAGE, $DESC)"

# Create README
echo "---> README"
echo "$DESC" > README.md
echo "========================================================================" >> README.md

# Create ChangeLog
echo "---> ChangeLog"
echo "$DESC ChangeLog" > ChangeLog.md
echo "========================================================================" >> ChangeLog.md
echo "" >> ChangeLog.md
echo "## ?.?.? / ????-??-??" >> ChangeLog.md
echo "" >> ChangeLog.md
echo "* Heads up: Converted classes to PHP 5.3 namespaces - (@thekid)" >> ChangeLog.md
echo "" >> ChangeLog.md

# Create class path file
echo "---> Class path"
find src/ -mindepth 2 -maxdepth 2 -type d > class.pth

# Convert main to namespaces
echo "---> Namespaces"
xpcli -cp ../../xp.experiments/ns-convert/ ConvertToNamespaces src/main/php

# Convert unittests
xp -cp ../_tools/ MoveTests src/test/php/ net.xp_framework.unittest.$PACKAGE $PACKAGE.unittest

echo "===> Done"
git st
```

**Comment by thekid** [comment]
@kiesel - what do you think, should we continue like this?

The workflow is as follows:
1. Create new repository, e.g. `xp-framework/rdbms` using the GitHub frontend
2. Add all paths to a file `echo src/main/php/rdbms src/test/php/net/xp_framework/unittest/rdbms src/test/resource/... > rdbms`
3. Run `sh extract.sh rdbms` to verify the commands
4. Run `sh extract.sh rdbms -e` to actually execute the extraction - _then wait very long_
5. Clone the new repository, e.g. `git clone git@github.com:xp-framework/rbdms.git`
6. Change the directory to there and run `modularize.sh`
7. Remove the above directories and the unittest configuration from xp.public/core
8. Run the tests, fix up things, repeat
9. Push the changes in this repo, then in xp.public/core, referencing this RFC via `xp-framework/rfc#262`.
10. Add webhook using the GitHub frontend

:coffee:

**Comment by kiesel** [comment]
I think so, you've already made it quite simple :-)

### Some other notes:
- We should also add builds on ci.planet-xp.net which run the Maven world builds
- When pushing all those commits to a new repo, GitHub sees these commits as _new_, effectively mailing `@mention`-commits to mentioned users (I've just been mailed a few times). Nothing serious, but remember it.
- `xp-maven-plugin` must be adapted when we change the name `xp-framework:core` to something else.

**Comment by thekid** [comment]
> We should also add builds on ci.planet-xp.net which run the Maven world builds

Good idea! This could be done using the Jenkins API AFAIS - and at the same time we integrate all thse with Travis-CI.

> I've just been mailed a few times

Yep, same goes for me. I don't see how we could suppress this, though...

**Comment by thekid** [comment]
:arrow_backward: I've undone the change with extracting the `security` package in xp-framework/core@ae6d4d3 and xp-framework/core@f324442 - the reason is it's used by quite a bit of APIs, e.g. Compressing streams in `io.streams` and the `CryptoSocket` base class for SSL and TLS support in `peer`.

**Comment by thekid** [comment]
:bulb: While we're going we can definitely see the need for module dependencies of some sort evolving:
- The REST APIs depend on Scriptlets, HTTP, JSON and XML
- The injection mechanisms (e.g. in xpcli, scriptlets, ...) depend on rdbms
- RDBMS Generators depend on XML
- Scriptlet depends on XML
- Core tests depend on unittest, which depends on core

The latter may be solved by declaring unittests part of the core (without mock and web, for example); but other situations clearly show the need for this. A possible solution may be RFC #204.

**Comment by thekid** [comment]
Fixed broken build due to classes reyling on **xml** APIs being available by adding the following to the tests causing these problems:

``` php
#[@beforeClass]
public static function onlyWithXmlModule() {
  if (!class_exists('xml\Tree')) {
    throw new \unittest\PrerequisitesNotMetError('XML Module not available', NULL, array('loaded'));
  }
}
```

If this needs to persist, this should be wrapped in a `unittest.actions.ModuleAvailable` class.

**Comment by thekid** [comment]
What's left:

``` sh
core = {
  lang {
    lang.archive
    lang.reflect
    lang.types
  }
  io {
    io.archive { io.collections { io.collections.iterate } }
    io.streams
    io.sys
  }
  math
  peer {
    peer.net
    peer.server { peer.server.protocol }
  }
  security {
    security.auth
    security.cert
    security.checksum
    security.crypto
    security.password
    security.sasl
  }
  text {
    text.encode
    text.format
    text.parser
    text.regex
    text.util
  }
  unittest {
    unittest.actions
    unittest.mock { unittest.mock.arguments }
    unittest.web
  }
  util {
    util.cmd
    util.collections
    util.log { util.log.context, util.log.layout }
    util.profiling
  }
  xp {
    xp.command
    xp.install
    xp.runtime
    xp.unittest { xp.unittest.sources }
    xp.xar { xp.xar.instruction }
  }
}
```

**Comment by thekid** [comment]
The `unittest` package is retained since the unittest API is used to test the core itself, but also depends on the core, thus yielding a recursive dependency, as [stated above](https://github.com/xp-framework/rfc/issues/262#issuecomment-28247818).
