### ISSUE TITLE
RFC process to use git pull requests

### ISSUE THREAD

**Issue by kiesel** [xp-framework/rfc#264]
# Scope of Change

The RFC process over the xp-framework/rfc repository will be changed in a way such that new RFCs will be done using GitHub pull requests.
# Rationale

Today, RFCs are GitHub issues - which is an improvement over the previous workflow by adding files to a repository, as that lacked any comment functionality other than adding that comment to the file in question.

This proposal's workflow allows for
- adding the RFC as file in a repository
- adding additional files ("contrib")
- discussing the RFC before acceptance through GitHub's web interface
- changing the RFC while a discussion takes place, keeping a history of what was changed when
- searchability over all RFCs (by `grep`)
# Functionality

Starting an RFC will include these steps:
1. Fork xp-framework/rfc if you don't have one, yet
2. Create a branch for your RFC
3. Create a new file in [directory]/rfc.md (see naming below)
4. Fill rfc.md with life
5. Optionally, add contributing files into the [directory]/contrib/
6. Once satisfied with the contents, create a pull request for your branch
7. Assign the pull request the `discussion` tag, so other contributors will start commenting it
8. After reaching an agreement on the RFC, merge it into xp-framework/rfc
9. That's it.
### Naming

Each RFC will have a unique number, but when initially creating the directory it is not yet available as only creating the pull request reliably assigns that number to the RFC.

So, until the pull request will be created, leave the number on a 4-digit zero value; then, after you have been assigned the number, move it to the respective name.

The naming scheme for the directory is:
`[RFC-number]-[URL-embeddable-speaking-RFC-name]`

Example: `0264-RFC_process_to_use_pull_requests`.
# Security considerations

n/a
# Speed impact

n/a
# Dependencies

n/a
# Related documents

**Comment by thekid** [comment]
:+1:

**Comment by thekid** [comment]
For naming, why not stick to the 4-number-scheme we had before? This here would be RFC `0264`. Maybe we can add "SEO"-style stuff like `0264-use-pull-requests-for-rfcs` to have a more speaking name.

**Comment by thekid** [comment]
Will you provide a script to convert all existing RFCs?

**Comment by kiesel** [comment]
@thekid: added naming convention; I will also provide a script.

**Comment by thekid** [comment]
> added naming convention

Cool!
