### ISSUE TITLE
XPI - Install XP modules

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#270]
# Scope of Change

The "xpi" command _currently used for upgrading the XP Runners_ will be dedicated to the purpose of discovering, installing, upgrading and removing XP modules.
# Rationale

With the separation of contrib & framework versions introduced in RFC #210 there is no longer an easy way to fetch releases of contrib modules. Previously, the modules were released together with an XP Framework release in the same release directory and could easily be fetched from there.
# Functionality

The entry point for working with modules will be the "xpi" command. It will allow the user to manage XP modules. 
## Modules

XP Modules have a name and a vendor, a description, a URL and any number of releases. On GitHub, the name is the repository's, the description the one-liner you enter beyond the repository's name, the URL the link to the overview page of it and the vendor is the user or organization that holds this repository.
### Example

```
+- Vendor "xp-framework"
|  |
|  ` Module "xp-language"
|    `- Release 1.9.0RC1
|
`- Vendor "xp-forge"
   |
   +- Module "mustache"
   |  |- Release 0.9.0
   |  `- Release 1.0.0
   |
   `- Module "gsa-xmlfeed" (no releases yet)
```

Modules are addressed by their compound name which is composed of the vendor and the module name, joined by a forward slash "/". Thus, the compound name of the "mustache" module will be `xp-forge/mustache`. 

Releases can be referenced by the compound name of the module and the release's version number, joined by the "@" sign. Mustache 1.0.0 is referenced as `xp-forge/mustache@1.0.0`. Version numbers must match the pattern `%d.%d.%d%s`, that is, the following are valid:
- 1.0.0
- 5.9.0RC8
- 5.8.0~unicodeRC1

---
## Module registry

Installable XP modules are maintained in a registry with a REST API on top of it. It provides discovery capabilities such as searching and listing, and provides  meta information for vendors, modules, their releases and downloads.
#### GET /search?q={query}

This will search for modules with either their local or compound name:

``` json
[
  {
    "module" : "stomp",
    "vendor" : "xp-forge",
    "link"   : { "url" : "https://github.com/xp-forge/stomp" },
    "info"   : "STOMP client classes for XP Framework: Publish and subscribe"
  }
]
```
#### GET /vendors

This will list all registered vendors.

``` json
[ { "vendor" : "xp-forge" }, { "vendor" : "xp-framework" } ]
```
#### GET /vendors/{vendor}

This will show information about a registered vendor. The output will include modules' names as a list of strings. If the vendor doesn't exist, a 404 Not found will be returned.

``` json
{
  "vendor"  : "xp-forge" , 
  "modules" : [ 
    "stomp", "mustache", "gsa-xmlfeed", /* ...  */
  ] 
}
```
#### GET /vendors/{vendor}/modules

This will list all modules for a given vendor. If the vendor doesn't exist, a 404 Not found will be returned.

``` json
[
  {
    "vendor"   : "xp-forge",
    "module"   : "stomp",
    "info"     : "STOMP client classes for XP Framework: Publish and subscribe",
    "link"     : { "url" : "https:\/\/github.com\/xp-forge\/stomp" },
  },
  {
    "vendor"   : "xp-forge",
    "module"   : "stomp",
    /* ... */
  }
}
```
#### GET /vendors/{vendor}/modules/{module}

This will show information about a registered vendor's module. The output includes a map containing information about the available releases. If the vendor or the module doesn't exist, a 404 Not found will be returned.

``` json
{
  "vendor"   : "xp-forge",
  "module"   : "stomp",
  "info"     : "STOMP client classes for XP Framework: Publish and subscribe",
  "link"     : { "url" : "https:\/\/github.com\/xp-forge\/stomp" },
  "releases" : { 
    "1.2.3RC1" : { "series" : "1.2", "rc" : true, "published" : "2013-03-19T19:05:50+01:00" } 
  }
}
```
#### GET /vendors/{vendor}/modules/{module}/releases

This will show all releases for a registered vendor's module. If the vendor or the module doesn't exist, a 404 Not found will be returned.

``` json
[
  {
    "module"    : "stomp",
    "vendor"    : "xp-forge",
    "version"   : { "number" : "1.2.3RC1", "series" : "1.2" },
    "published" : "2013-03-19T19:05:50+01:00",
  }
]
```
#### GET /vendors/{vendor}/modules/{module}/releases/{release}

This will show information about a specific release. If the vendor, module or release don't exist, a 404 Not found will be returned.

``` json
{
  "module"    : "stomp",
  "vendor"    : "xp-forge",
  "version"   : { "number" : "1.2.3RC1", "series" : "1.2" },
  "published" : "2013-03-19T19:05:50+01:00",
  "files"     : [
    {
      "link" : "/vendors/xp-forge/modules/stomp/releases/1.2.3RC1/xp-stomp-1.2.3RC1.xar",
      "sha1" : "3da02d450ee95f85f73fa25a178a3faacb79aebe",
      "name" : "xp-stomp-1.2.3RC1.xar",
      "size" : 28611
    },
    {
      "link" : "/vendors/xp-forge/modules/stomp/releases/1.2.3RC1/xp-stomp-test-1.2.3RC1.xar",
      "sha1" : "85898b62024bc1decfce99051e09788155e66d7b",
      "name" : "xp-stomp-test-1.2.3RC1.xar",
      "size" : 17415
    }
  ]
}
```

---
## The XPI utility

This command line tool uses the registry described above and manages modules in the current working directory. The registry defaults to the default XP module registry available at http://builds.planet-xp.net/.
### Basic usage

The basic operations are _search_ and _info_ for discovery, _add_, _list_, _upgrade_ and _remove_ for CRUD operations.

``` sh
# This will search for modules
$ xpi search "query"

# This will show information about a module, and its releases (newest first)
$ xpi info vendor/module

# This will install the newest release of the specified module and select it
$ xpi add vendor/module

# This will list installed modules
$ xpi list

# This will upgrade the module to the newest release
$ xpi upgrade vendor/module

# This will remove the module
$ xpi remove vendor/module
```

The _info_ command is actually overloaded and will display information about locally installed modules when it finds them installed. This behavior may be controlled by using the command line switches `-i` (installed) and `-r` (remote).
### The local file system structure

The command line tool creates a folder for each vendor, and subfolders and a meta information file for each module. It also generates path files for adding the modules to the class path.

```
+- xp-framework/
|  |- xp-language.json
|  `- xp-language@1.9.0RC1/
|     |- class.pth
|     |- xp-compiler-1.9.0RC1.xar
|     `- xp-compiler-test-1.9.0RC1.xar
|
|- xp-forge/
|  |- mustache.json
|  `- mustache@1.0.0/
|     |- class.pth
|     |- xp-mustache-1.0.0.xar
|     `- xp-mustache-test-1.0.0.xar
|
|- .xp-framework.xp-language@1.9.0RC1.pth
`- .xp-forge.mustache@1.0.0.pth
```
### Working with versions

Most of the time, it is fine to work with just one version of a certain module, which is also the newest version. In certain situations, this can not be desirable. The "xpi" utility therefore supports having multiple versions of a module installed (though only one can be "selected" per time).

Given we have `xp-forge/mustache@1.0.0` installed as seen above and want to play around with the most recent RC, we can do the following:

``` sh
$ xpi add xp-forge/mustache@1.1.0RC2
```

This will install the **1.1.0RC2** release **parallel** to the existing **1.0.0** and select it to be the active one. We can see this in `xpi info`'s output, the releases list will include both, and the selected one will be shown at the bottom.

When we are done playing around and want to go back to the version we'd previously been using, we'll just remove that:

``` sh
$ xpi remove xp-forge/mustache@1.1.0RC2
```
### Using development branches

Sometimes, it can be necessary to use development branches. Any version identifier not matching the version pattern `%d.%d.%d%s` is regarded a branch name.

``` sh
# This will install the "master" branch of the specified module from GitHub
$ xpi add vendor/module@master
```

**Important: The only source location supported are public GitHub repositories!**

---
### Global setup (or per-user)

In order to install the modules in a way that they will be accessible in any situation, the modules should be referenced via `xp.ini`'s `use` directive. The simplest way is to use the same directory as the ini file resides in for your modules, and the reference it relatively:

``` ini
use=~/devel/xp/5.9.0RC8;.
```

**Important: (On Un*x, use ":" to separate the paths!)**
### Per-project setup

If the modules only serve a local purpose to a project, it's easier to copy them to a `lib` directory:

``` sh
$ cd my-project
$ mkdir lib
$ cd lib
$ xpi add xp-forge/stomp
$ cd ..
$ cat lib/*pth > lib.pth
```

---
## Example

Let's start with an empty modules directory:

``` sh
$ xpi list
@F:\...\devel\modules\

0 module(s) installed
```

Then, we decide to install the mustache library, so we search for it

``` sh
$ xpi search mustache
Module<xp-forge/mustache>: The Mustache Template engine for the XP Framework

1 result(s) found.

$ xpi info xp-forge/mustache
@http://builds.planet-xp.net/
Module<xp-forge/mustache>: The Mustache Template engine for the XP Framework
https://github.com/xp-forge/mustache
Releases: 2, list {
  1.0.0 (series= "1.0", rc= false, published= "2013-04-09T03:08:58+02:00")
  0.9.0 (series= "0.9", rc= false, published= "2013-04-07T16:43:33+02:00")
}
```

...and add it:

``` sh
$ xpi add xp-forge/mustache
Using latest release 1.0.0
Module<xp-forge/mustache> -> io.Folder(uri= F:\...\devel\modules\xp-forge\mustache@1.0.0\)
Release 1.0.0 published 2013-04-09T03:08:58+02:00
>> xp-mustache-1.0.0.xar
>> xp-mustache-test-1.0.0.xar
Select io.File(uri= .xp-forge.mustache@1.0.0.pth, mode= wb)
Done
```

Also, let's get the XP Compiler:

``` sh
$ xpi add xp-framework/xp-language
Using latest release 1.9.0RC1
Module<xp-framework/xp-language> -> io.Folder(uri= F:\...\devel\modules\xp-framework\xp-language@1.9.0RC1\)
Release 1.9.0RC1 published 2013-04-14T12:20:06+02:00
>> xp-compiler-1.9.0RC1.xar
>> xp-compiler-test-1.9.0RC1.xar
Select io.File(uri= .xp-framework.xp-language@1.9.0RC1.pth, mode= wb)
Done
```

After all this (somewhat verbose) output, let's see where we are now:

``` sh
$ xpi list
@F:\...\devel\modules\
Module<xp-forge/mustache>: The Mustache Template engine for the XP Framework
Module<xp-framework/xp-language>: XP Compiler and Language

2 module(s) installed

```

...and finally, let's get rid of the mustache library again:

``` sh
$ xpi remove xp-forge/mustache
Removing active io.Folder(uri= F:\...\devel\modules\xp-forge\mustache@1.0.0\)
Done
```
# Security considerations
# Speed impact
# Dependencies
# Related documents
- [XP build system](https://github.com/xp-framework/build)
- RFC #91 - XP Versions
- RFC #178 - XP Installations

**Comment by thekid** [comment]
Announced here: http://news.planet-xp.net/article/515/2013/04/22/

**Comment by mrosoiu** [comment]
I'm not a big fan of home-made package management solutions (E.g: npm, cpan, pyrus). IMO, there are already other industry-standard software management alternatives.

I see 2 uses of XP-Framework & modules:

###### Case 1 - You want to develop a project (website, xpcli)

In this case, what you really want from a package management solution is:
- Download required modules (sources or `.xar` packages)
- Create a `.pth` file to reference them

My proposed solution is to use Maven:

``` sh
$ mkdir ~/my_project && cd my_project
$ vim pom.xml
  -> set project coordinates and add required dependencies (core, webservices, scriptlet, etc.)
$ mvn xp:ignite
  -> this will download specified dependencies into ~/my_project/lib and create the correct .pth file
  -> see xp-maven-plugin
```

Pros:
- Take advantage of Maven's standard directory structure, dependency resolution, ecosystem (customizable build process via Maven plugins, Maven Central repository), etc.
- Isolated run: does not even require to have XP-Framework runners installed on local machine

Note: This works on all platforms where Maven runs (*nix, windows, mac)

###### Case 2 - You want XP-Framework installed on local system to be used via command line

You can go further and create `.sh` scripts with an XP-Framework shebang `#!/usr/bin/xp`

My proposed solution is to use the OS's package management system: apt, emerge, yum, pacman:

``` sh
$ sudo aptitude install xp-framework xp-webservices xp-scriptlet
```

Maintaining repositories for all those package management systems might be a bit tedious to setup, but once in place updating them can be done automatically via release hook scripts.

Pros:
- We can automatically install PHP and required PHP extensions when someone tries to install XP-Framework, or even install Apache if the "xp-scriptlet" package is installed
- Ease the life of the IT Ops/deploy team (no additional knowledge on how to use yet another tool `xpi`, install XP-Framework via puppet as any other software)
- Standard directories: no home-made directory structure, files are where you expect them to be (on Debian-based distros: `/etc/xp.ini`, `/usr/bin/xpcli`, `/usr/lib/xp/...`, etc.)

Cons:
- Windows does not have a package management system; we can go around this using the WiX Toolset to create setup `.exe` packages to install XP-Framework in standard location `C:\Program Files\xp-framework`

**Comment by thekid** [comment]
Re your comment, @mrosoiu:
- Case 1 - Cons: We depend on yet another piece of software (actually on two, as Maven depends on Java), both of which I need to have installed.
- Case 2 - Cons: Most package managers I've come across don't allow per-user installation.

I have nothing against other possibilities to set up the XP Framework, and have actually [created .deb files](http://news.planet-xp.net/article/394/2010/12/16/apt-get_meets_the_XP-Framework) myself a while back (but not automated this process) because of the per-user requirement.

This RFC follows the "make it easy to setup stuff" strategy introduced with our `wget ... | php` solution a couple of years back, and brings a self-contained installation mechanism to the XP Framework. Yes, it does not do dependencies (and yes, that reduces the complexity for the software about 99.9%). Yes, you can also use maven. Or composer  - [I also tried that actually](https://github.com/thekid/composer). Or even npm, if you wish. "xpi" does not try to be better than these. 

"xpi" aims to be the minimum possible solution XP Technology brings with itself; instead of having to write lengthy manuals on how to setup and integrate other pieces of software, or having to explain manual downloads of the XAR files. Kind of like Windows bringing notepad.exe, but leaving it up to the user to install SublimeText:)

**Comment by thekid** [comment]
Nobody at least seems to _object_ to adding this -> merging this.

**Comment by thekid** [comment]
Short introduction @ http://news.planet-xp.net/article/522/2013/05/05/XPI
