### ISSUE TITLE
XP Language Repository reorganization

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#274]
# Scope of Change

The "xp-language" repository will be reorganized and split into compiler and tools.
# Rationale
- Clear up versioning inconsistencies by using another artifactId, ease Maven builds
- Be able to use shorter repository names
- Enable further modularization
# Functionality

The repository https://github.com/xp-lang/xp-language will be split into:
1. The "compiler" subdirectory
   Contains the compiler, with PHP and XP syntax support

```
https://github.com/xp-lang/compiler
|- src 
|  |- main/php
|  `- test/php
|- ChangeLog
`- README.md
```
1. The "tools" subdirectory
   Currently contains only one tool, a PHP -> XP syntax converter

```
https://github.com/xp-lang/convert
|- src 
|  |- main/php
|  `- test/php
|- ChangeLog
`- README.md
```
# Security considerations

n/a
# Speed impact

n/a
# Dependencies
- Users relying on the development checkout will have to change their `use` statement from `use=~/xp-framework/core;~/xp-language/compiler` to `use=~/xp-framework/core;~/compiler` (or move directories accordingly!)
- XPI Users will need to `xpi remove xp-framework/xp-language` and then `xpi add xp-lang/compiler`. XPI doesn't support redirects, or deprecation messages, or any facility to ease this. There just won't be any new releases on the old vendor's module.
# Related documents
- [The discussion that motivated this RFC](https://github.com/xp-forge/stomp/commit/fb07c6189d0b9a87bb02371a055e209655873e9e#commitcomment-3282011)
- RFC #260 describes how subdirectories can be extracted into own repositories and contains [a script for this](https://github.com/xp-framework/rfc/issues/260#issuecomment-11858337)

**Comment by thekid** [comment]
Announcement @ http://news.planet-xp.net/article/537/2013/05/27/RFC-0274

**Comment by mrosoiu** [comment]
+1

Shouldn't it be `xpi add xp-lang/compiler` ?

**Comment by kiesel** [comment]
:+1:

**Comment by thekid** [comment]
> Shouldn't it be xpi add xp-lang/compiler ?

Erm, yes:) Thanks, fixed!

**Comment by thekid** [comment]
Extracting the "tools" directory into https://github.com/xp-lang/convert

``` sh
$ git filter-branch --subdirectory-filter tools master -- --all
$ git reset --hard
$ git gc --aggressive
$ git prune
$ git remote rm origin
$ git remote add origin git@github.com:xp-lang/convert.git
$ git push origin master
```

:ok:

**Comment by thekid** [comment]
Rename https://github.com/xp-lang/xp-language to https://github.com/xp-lang/compiler so we keep all the issues / pull requests / wiki etc.

:ok:

**Comment by thekid** [comment]
Moving the `compiler` subdirectory into the top-level directory:

``` sh
$ git rm -r tools
$ git mv compiler/* .
$ git ci -m '- Reorganize paths' .
$ s README.md xpbuild.json 
$ git rm xpbuild.json
$ git ci -m '- Change paths' README.md xpbuild.json .travis.yml
$ git push
```

:ok: - see https://travis-ci.org/xp-lang/compiler/builds/7538327

**Comment by thekid** [comment]
Register `xp-lang` as vendor in build system:

``` sh
$ ssh cgi@xpsrv.net
$ mkdir -m 0777 /home/httpd/xp.php3.de/doc_root/downloads/builds/xp-lang
$ logout
$ xpi info xp-lang/compiler
@http://builds.planet-xp.net/
Module<xp-lang/compiler>: XP Compiler and Language
https://github.com/xp-lang/compiler
Releases: 0, list {
}
```

:ok:

**Comment by thekid** [comment]
Create first release:

``` sh
$ grb tag r1.10.3
$ xpi info xp-lang/compiler
@http://builds.planet-xp.net/
Module<xp-lang/compiler>: XP Compiler and Language
https://github.com/xp-lang/compiler
Releases: 1, list {
  1.10.3 (series= "1.10", rc= false, published= "2013-05-27T18:25:30+02:00")
}
```

:ok: (ChangeLog commit: xp-lang/compiler@f2b1994920ff817655127ce95506827e646b5b7b)

**Comment by thekid** [comment]
Verified xpi / development checkout changes work as documented above

:ok:

**Comment by thekid** [comment]
Re-released all releases under the new vendor/module coordinates `xp-lang/compiler`.

``` sh
cgi@xpsrv ~/build.xp-framework.net/web $ for rel in 1.10.2 1.10.1 1.10.0 1.10.0RC2 1.10.0RC1 1.9.0 1.9.0RC1 ;
  do USE_XP=../5.9.2/ xpcli -c etc/prod/ net.xp_framework.build.subscriber.TriggerBuild xp-lang/compiler $rel ; 
done
cgi@xpsrv ~/xp.php3.de/doc_root/downloads/builds $ for i in `ls -1d xp-lang/compiler/1*`; 
  do v=`basename $i` ; touch -m -r xp-framework/xp-language/$v $i ; 
done
```

...and here they are:

``` sh
$ xpi info -r xp-lang/compiler
@http://builds.planet-xp.net/
Module<xp-lang/compiler>: XP Compiler and Language
https://github.com/xp-lang/compiler
Releases: 8, list {
  1.10.3 (series= "1.10", rc= false, published= "2013-05-28T08:31:48+02:00")
  1.10.2 (series= "1.10", rc= false, published= "2013-05-20T16:50:51+02:00")
  1.10.1 (series= "1.10", rc= false, published= "2013-05-14T22:56:29+02:00")
  1.10.0 (series= "1.10", rc= false, published= "2013-05-12T19:05:00+02:00")
  1.10.0RC2 (series= "1.10", rc= true, published= "2013-05-10T14:23:59+02:00")
  1.10.0RC1 (series= "1.10", rc= true, published= "2013-05-10T11:38:35+02:00")
  1.9.0 (series= "1.9", rc= false, published= "2013-05-05T14:36:27+02:00")
  1.9.0RC1 (series= "1.9", rc= true, published= "2013-04-14T12:20:06+02:00")
}
```

:ok:

**Comment by thekid** [comment]
Blog @ http://news.planet-xp.net/article/538/2013/05/28/XP_Compiler_in_new_GitHub_organization
