### ISSUE TITLE
Map class URIs to classes

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#275]
# Scope of Change

A new method will be introduced in the class loading infrastructure to map class URIs to class objects.
# Rationale

In several places, mapping class URIs back to classes / class names is necessary. Two examples:
- Code coverage (see e.g. kiesel/xp-framework@54cd0acd2de0d828878307ef4af9ae8968d3860e)
- Command line parameters, enabling tab completion (unittest src/test/php/...Test.class.php, `xp -r`)
# Functionality

A new method `loadUri` will be added to the `lang.ClassLoader` class. It will check all delegates, asking their `loadUri` method. The first delegate to return non-null will be considered the provider of this class.
### Class loader API extensions

The following new methods will be added:

``` groovy
public bool providesUri(string $uri)
public lang.IClassLoader findUri(string $uri)
public lang.XPClass loadUri(string $uri) throws lang.ClassNotFoundException
```

These resemble the `providesClass()`, `findClass()` and `loadClass()` methods except that they work with URIs, obviously.
### Example: Use command line argument to find class

``` php
$cl= ClassLoader::getDefault();
if (!$cl->providesUri($argv[0])) {
  Console::$err->writeLine($argv[0], ' is not provided by any class loader');
  return;
}

$class= $cl->loadUri($argv[0]);
Console::writeLine($argv[0], ' maps to a class named ', $class->getName());
```
### Example: Determine which class loader provides a class

``` php
$cl= ClassLoader::getDefault()->findUri($argv[0]);
if (is(NULL, $cl)) {
  Console::$err->writeLine($argv[0], ' is not provided by any class loader');
  return;
}

Console::writeLine($argv[0], ' is provided by ', $cl);

// Then load it directly from the found class loader
$class= $cl->loadUri($argv[0]);
```
# Security considerations

n/a
# Speed impact

n/a
# Dependencies

n/a
# Related documents

Announcement @ http://news.planet-xp.net/article/545/2013/07/11/RFC-0275

**Comment by thekid** [comment]
Not happy with the name _classAtUri()_, maybe use one of these alternatives:
- [ ] `mapToClass` (Alex' suggestion)
- [ ] `loadFile` (like loadClass, which loads by fully qualified class name, but should raise exception then!)
- [ ] `loadUri` (-~-)
- [ ] `loadUri` + `findUri`
- [ ] `classOfUri`
- ...

**Comment by mikey179** [comment]
Probably `classFromUri`?

**Comment by kiesel** [comment]
I second Frank's proposal, `classFromUri` sounds good.

**Comment by thekid** [comment]
Changed RFC to use `classFromUri` instead of `classAtUri`. The _from_ sounds more like something is being made / created from the URI, while _at_ is more like finding something already existing.

**Comment by thekid** [comment]
For the same reason - `classFromUri()` is an imperative to create a class from a URI and doesn't sound like _"see if you can find something, if not, it's still OK"_ - I believe though this method should throw an exception instead of returning `null`.

**Comment by kiesel** [comment]
From the usecase in the test-coverage, the workflow is:
- check if a class exists at a given path
- retrieve a found class' bytes (through the loader, which can be accessed through the `XPClass` object)

It should be possible to achieve this w/o causing exceptions. 

Also, I also would like to avoid actually loading a new class from a uri when just checking...

**Comment by thekid** [comment]
Initial <del>and incomplete</del> implementation @ https://github.com/thekid/xp-framework/compare/rfc-275

_Update (Aug. 19th): No longer incomplete, pull request created_

**Comment by thekid** [comment]
Re-thinking the method names, I now think `loadUri()` + `providesUri()` (analog to `loadClass()` + `providesClass`, `getResource()` + `providesResource`) sound better. Also, I think we should make `classUri()` public so that `$fixture->loadUri($fixture->classUri('fully.qualified.ClassName'))` works (useful e.g. in test cases).

I've updated the pull request accordingly.
