### ISSUE TITLE
Bump PHP version requirement to PHP 5.4

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#281]
# Scope of Change

The minimum required PHP version for XP 6 will be bumped to PHP 5.4.0 minimum.
# Rationale

Be able to make use of traits, array dereferencing,  `(new foo)->bar())`, short array syntax, closure $this support.
# Functionality
### Traits for core objects

We could let the compiler copy&paste functionality common to `lang.Object` and `lang.Throwable` from a trait. See xp-framework/xp-framework#77 for an implementation idea and performance impact.
### Interface evolution

We could revisit the issue of default implementations of interface methods as shown in [this experiment](https://github.com/thekid/xp-experiments/tree/master/intf-evolution).
### Remove checks for setAccessible

The method Reflection[Method|Property]::setAccessible() was not usable before PHP 5.3.2. We can now remove these checks.
# Security considerations
# Speed impact
# Dependencies
# Related documents
- http://de3.php.net/ChangeLog-5.php#5.4.0 - PHP 5.4 ChangeLog
- https://wiki.php.net/rfc/php53eol - Define PHP 5.3 end of life

**Comment by kiesel** [comment]
Of course, this will rule out platforms where only PHP <5.4 is available (eg. Debian Wheezy), but I think it's worth it. 5.4 has become wide-spread since first release.

:+1:

**Comment by thekid** [comment]
- [x] Adapt PHP 5.4.0 officially xp-framework/core@9315649

**Comment by thekid** [comment]
- [x] Traits for core objects xp-framework/core@bdcbea7

**Comment by thekid** [comment]
- [x] Removed quite a bit of PHP 5.3 specific checks

**Comment by thekid** [comment]
- [x] Rewrote all occurences of `create(new ...)` -> `(new ...)` in xp-framework/core@65635d0

**Comment by thekid** [comment]
- [x] Rewrote all occurences of empty `array()` statements -> `[]` in xp-framework/core@aa15d69
- [x] Rewrote all non-empty array statements to [...] in lang package in xp-framework/core@a8348f0

**Comment by thekid** [comment]
Part of XP 6, see #172
