### ISSUE TITLE
Coding standards: Compact APIdocs

### ISSUE THREAD

**Issue by thekid** [xp-framework/rfc#284]
# Scope of Change

This RFC suggests to remove the need for API documentation when declaring getters and setters. 
# Rationale

Reduce noise.
# Functionality

Currently, all methods should have API documentation. This results in very noisy code for getters and setters:

``` php
class Example extends Object {
  protected $id;

  /**
   * Gets the id
   *
   * @return int
   */
  public function getId() {
    return $this->id;
  }

  /**
   * Sets the id
   *
   * @param int $id
   */
  public function setId($id) {
    $this->id= $id;
  }
}
```

That's 16 lines to express a very simple concept!

The suggestion goes along the lines of C#’s properties and shortens this to the following:

``` php
class Example extends Object {
  protected $id;

  /** @return int */
  public function getId() { return $this->id; }

  /** @param  int $id */
  public function setId($id) { $this->id= $id; }
}
```

As you can see, the code is now down to 5 lines.
# Security considerations
# Speed impact
# Dependencies

No changes necessary.
# Related documents
- https://github.com/xp-framework/xp-framework/wiki/codingstandards Current coding standards
- RFC #208 - PHP 5.3 coding standards update
- http://msdn.microsoft.com/en-us/library/aa664452(v=vs.71).aspx Accessors, C#
- RFC #241 - Compact method syntax
- https://wiki.php.net/rfc/propertygetsetsyntax-v1.2

**Comment by thekid** [comment]
Another idea would be to have a special syntax for getters, e.g.

``` php
#[@type('int')]
protected $id;

/** get('id') */ function getId() { return $this->id; }

Alternative syntax:

/** @get */ - API-doc tag
/** :get */ - Ruby identifier 
/** #get */ - inspired by annotations 
/** get() */ - like in Typescript and the PHP RFC
```

For performance reasons, we'll use doc comments which are available via PHP core reflection instead of parsing from code.

**_Update (19.05.):**_ _I feel this goes too far, the optimization possible with current semantics already work just fine to shorten the lines drastically_

**Comment by mikey179** [comment]
I'm not sure if this isn't the kind of optimization that makes ugly things too simple. I tend to think that Getters and Setters in general are overused and lead to non-OO-code. Making them even easier to write because you would have to write less is the wrong direction.

**Comment by thekid** [comment]
It would also work for your `/** get */ function id() { ... }` without a setter, @mikey179 :)

**Comment by mikey179** [comment]
Sure. :) But people tend to write too much of them. Making it easier to do the wrong thing is not a particularly good idea. See Threads in Java. ;-)
Also, when I have model classes which resemble business objects I want to have a good documentation on their accessors - at least telling how this part is related to the business logic and what I can do with it. See https://github.com/mikey179/releaseIt/blob/master/src/main/php/org/bovigo/releaseit/Series.php and https://github.com/mikey179/releaseIt/blob/master/src/main/php/org/bovigo/releaseit/Version.php for examples where not the properties itself are exposed but functionality based on that data.

**Comment by thekid** [comment]
Here's a [real life example](https://github.com/xp-framework/glue/blob/master/src/main/php/xp/glue/Dependency.class.php) of what this would look like.

**Comment by thekid** [comment]
Accepted!

**Comment by thekid** [comment]
Updated coding standards section "Comments"

https://github.com/xp-framework/xp-framework/wiki/codingstandards#-comments
