### ISSUE TITLE
Expose database mock implementation

### ISSUE THREAD

**Issue by kiesel** [xp-framework/rfc#313]
# Scope of Change

The available mock implementation for database access that currently lives in `src/test` in the package `rdbms.unittest.mock` will be exposed to third party use by moving it tinto `src/main` and thus including it in the publicly available API.
# Rationale

Occurrances of usage have been observed; while it was possible to pick up the package, even though it was a test package, it is no longer possible since the introduction of Composer. Tests could benefit from being able to use mocks.
# Functionality

The available classes would be:
- `rdbms.unittest.mock.MockConnection`
- `rdbms.unittest.mock.MockResultSet`
- `rdbms.unittest.mock.MockDialect`
- `rdbms.unittest.mock.RegisterMockConnection` (which is a unittest @action class)

The `MockConnection` class can be used to _simulate_ rdbms sessions:

``` php
$conn= new MockConnection('...');
$conn->addResultSet(new MockResultSet(['id' => 1, 'value' => 'foo']);
```

This resultset will be delivered as the first row of a query.

Simulate server disconnects:

``` php
$conn= new MockConnection('...');
$conn->letServerDisconnect();

$conn->query('...'); // Oops!
```

Make server connect fail:

``` php
$conn= new MockConnection('...');
$conn->makeConnectFail();

$conn->query('...'); // Oh no!
```

... and some more.
# Security considerations

n/a
# Speed impact

n/a
# Dependencies
# Related documents
- It should be noted that using this implementation represents a very low-level way to test something; if there are ways to mock / replace higher level objects in the respective test, that way should be preferred.

**Comment by thekid** [comment]
> $conn->addResultSet(new MockResultSet(['id' => 1, 'value' => 'foo']);

Hrm, this is quite verbose. How about:

``` php
$conn->returnResult([['id' => 1, 'value' => 'foo']]);
```

**Comment by thekid** [comment]
> $conn->letServerDisconnect();
> $conn->makeConnectFail();

There should be a way to clear these again...

**Comment by thekid** [comment]
Maybe `Mock` is a too technical term. How about `Testing` (for both package and class)?
